import { StyleSheet } from 'react-native';
import { BG, GOLD, NAVY } from './constants';
import {
  heroBadgeBase,
  heroBadgeTextBase,
  heroCardBase,
  heroGlowBase,
  heroIconWrapBase,
  heroTextBase,
  heroTitleBase,
  heroTopRowBase,
} from '../shared/heroStyles';

export const badgesStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: BG },
  topInset: { backgroundColor: NAVY },
  header: {
    backgroundColor: NAVY,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: '700',
    flex: 1,
    textAlign: 'center',
  },
  content: {
    paddingHorizontal: 16,
    paddingBottom: 40,
    paddingTop: 20,
  },
  streakCard: {
    ...heroCardBase,
    paddingVertical: 24,
    marginBottom: 32,
  },
  streakHeroGlow: {
    ...heroGlowBase,
  },
  streakTopRow: {
    ...heroTopRowBase,
    marginBottom: 16,
  },
  streakBadge: {
    ...heroBadgeBase,
  },
  streakBadgeText: {
    ...heroBadgeTextBase,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  streakIconOrb: {
    ...heroIconWrapBase,
    width: 54,
    height: 54,
  },
  streakTitle: {
    ...heroTitleBase,
  },
  streakSubtitle: {
    ...heroTextBase,
    fontSize: 13,
    marginBottom: 18,
  },
  streakLabel: {
    fontSize: 13,
    color: '#888',
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  streakRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderRadius: 24,
    paddingVertical: 14,
    paddingHorizontal: 14,
    marginBottom: 18,
  },
  streakNumberShell: {
    minWidth: 106,
    minHeight: 106,
    borderRadius: 28,
    backgroundColor: '#FFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 4,
  },
  streakFire: { fontSize: 28 },
  streakNumber: { fontSize: 52, fontWeight: '900', color: NAVY },
  streakMetaColumn: {
    flex: 1,
    marginRight: 14,
    alignItems: 'center',
  },
  streakDays: {
    fontSize: 18,
    color: '#E9D6A1',
    fontWeight: '700',
    marginBottom: 6,
    textAlign: 'left',
  },
  streakHint: {
    color: 'rgba(255,255,255,0.62)',
    fontSize: 12,
    lineHeight: 20,
    textAlign: 'left',
  },
  streakProgressWrap: {
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderRadius: 22,
    padding: 14,
    marginBottom: 16,
  },
  streakProgressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  streakProgressValue: {
    color: GOLD,
    fontSize: 13,
    fontWeight: '800',
  },
  streakProgressLabel: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 12,
    fontWeight: '700',
  },
  streakProgressTrack: {
    width: '100%',
    height: 8,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 999,
    overflow: 'hidden',
  },
  streakProgressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: GOLD,
  },
  statsRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    justifyContent: 'space-between',
    width: '100%',
    gap: 10,
  },
  statBox: {
    alignItems: 'center',
    flex: 1,
    backgroundColor: '#FFF',
    borderRadius: 20,
    paddingVertical: 14,
    paddingHorizontal: 8,
  },
  statNum: { fontSize: 20, fontWeight: '700', color: GOLD },
  statLabel: {
    fontSize: 11,
    color: '#7A8594',
    marginTop: 4,
    textAlign: 'center',
    lineHeight: 16,
  },
  statDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#ddd',
  },
  badgesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  gallerySectionTitle: {
    color: NAVY,
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 14,
    textAlign: 'left',
  },
  spotlightCard: {
    backgroundColor: '#FFF',
    borderRadius: 28,
    padding: 18,
    marginBottom: 22,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.06)',
    shadowColor: '#0B1730',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 3,
  },
  spotlightGlow: {
    position: 'absolute',
    top: -20,
    right: -20,
    width: 140,
    height: 140,
    borderRadius: 70,
  },
  spotlightTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  spotlightPill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
  },
  spotlightPillText: {
    fontSize: 12,
    fontWeight: '800',
  },
  spotlightPillTextMuted: {
    color: '#667085',
  },
  spotlightIconWrap: {
    width: 58,
    height: 58,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  spotlightEmoji: {
    fontSize: 28,
  },
  spotlightTitle: {
    color: NAVY,
    fontSize: 28,
    fontWeight: '900',
    marginBottom: 4,
    textAlign: 'left',
  },
  spotlightDays: {
    color: '#7B8390',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 10,
    textAlign: 'left',
  },
  spotlightText: {
    color: '#445064',
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 14,
    textAlign: 'left',
  },
  spotlightProgressTrack: {
    width: '100%',
    height: 10,
    borderRadius: 999,
    backgroundColor: '#EEF2F6',
    overflow: 'hidden',
  },
  spotlightProgressFill: {
    height: '100%',
    borderRadius: 999,
  },
  badgeCard: {
    width: '48%',
    backgroundColor: '#FFF',
    borderRadius: 24,
    paddingVertical: 14,
    paddingHorizontal: 12,
    marginBottom: 16,
    alignItems: 'center',
    overflow: 'hidden',
    elevation: 2,
    shadowColor: '#0B1730',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
  },
  badgeCardEarned: {
    elevation: 5,
    shadowColor: GOLD,
    shadowOpacity: 0.16,
    shadowRadius: 16,
    transform: [{ translateY: -2 }],
  },
  badgeCardLocked: {
    opacity: 0.92,
  },
  badgeCardAccent: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 5,
  },
  badgeTopRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  badgeStatePill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  badgeStatePillEarned: {
    backgroundColor: 'rgba(201,168,76,0.12)',
  },
  badgeStatePillPending: {
    backgroundColor: '#F3F6FA',
  },
  badgeStateText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#6F7885',
    textAlign: 'center',
  },
  badgeDayChip: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  badgeDayChipText: {
    fontSize: 10,
    fontWeight: '800',
    textAlign: 'center',
  },
  badgeHalo: {
    width: 88,
    height: 88,
    borderRadius: 44,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  badgeRingBg: {
    position: 'relative',
  },
  badgeRing: {
    width: 72,
    height: 72,
    borderRadius: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeEmoji: { fontSize: 38 },
  checkmark: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  badgeTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: NAVY,
    textAlign: 'center',
    marginBottom: 4,
  },
  badgeSubtitle: {
    fontSize: 11,
    color: '#7B8491',
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: 10,
  },
  progressMetaRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  progressMetaText: {
    fontSize: 11,
    fontWeight: '800',
  },
  progressLabel: {
    fontSize: 11,
    color: '#8C95A1',
    fontWeight: '600',
  },
  progressBar: {
    width: '100%',
    height: 7,
    backgroundColor: '#EDF1F5',
    borderRadius: 999,
    overflow: 'hidden',
    marginBottom: 10,
  },
  progressFill: { height: '100%', borderRadius: 999 },
  earnedTag: {
    marginTop: 4,
    paddingVertical: 7,
    paddingHorizontal: 14,
    borderRadius: 999,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    alignSelf: 'center',
  },
  earnedText: { fontSize: 12, fontWeight: '700', textAlign: 'center' },
  pendingRow: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  pendingText: {
    fontSize: 11,
    color: '#7E8896',
    fontWeight: '700',
    textAlign: 'center',
  },
  motivationalCard: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    marginBottom: 32,
    paddingVertical: 16,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    gap: 12,
  },
  motivationalBody: { flex: 1, marginHorizontal: 12 },
  motivationalTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: NAVY,
    marginBottom: 4,
  },
  motivationalText: {
    fontSize: 12,
    color: '#666',
    lineHeight: 18,
  },
});
