import { StyleSheet } from 'react-native';
import { BG, GOLD, NAVY } from './constants';
import {
  heroBadgeBase,
  heroBadgeTextBase,
  heroCardBase,
  heroGlowBase,
  heroIconWrapBase,
  heroTextBase,
  heroTitleBase,
  heroTopRowBase,
} from '../shared/heroStyles';

export const badgesStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: BG },
  topInset: { backgroundColor: NAVY },
  header: {
    backgroundColor: NAVY,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: '700',
    flex: 1,
    textAlign: 'center',
  },
  content: {
    paddingHorizontal: 16,
    paddingBottom: 40,
    paddingTop: 16,
  },
  streakCard: {
    ...heroCardBase,
    borderRadius: 28,
    paddingVertical: 20,
    marginBottom: 16,
  },
  streakHeroGlow: {
    ...heroGlowBase,
    top: -72,
    left: -48,
    width: 220,
    height: 220,
    borderRadius: 110,
  },
  streakTopRow: {
    ...heroTopRowBase,
    marginBottom: 12,
  },
  streakBadge: {
    ...heroBadgeBase,
  },
  streakBadgeText: {
    ...heroBadgeTextBase,
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  streakIconOrb: {
    ...heroIconWrapBase,
    width: 48,
    height: 48,
    borderRadius: 16,
  },
  streakTitle: {
    ...heroTitleBase,
    fontSize: 22,
    lineHeight: 30,
    marginBottom: 6,
  },
  streakSubtitle: {
    ...heroTextBase,
    fontSize: 13,
    marginBottom: 16,
  },
  streakLabel: {
    fontSize: 13,
    color: '#888',
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  streakScorePanel: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 18,
    padding: 12,
    marginBottom: 12,
    gap: 12,
  },
  xpBlock: {
    flex: 1,
    alignItems: 'flex-start',
  },
  xpLabel: {
    color: 'rgba(255,255,255,0.68)',
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 3,
    textAlign: 'left',
  },
  xpNumber: {
    color: GOLD,
    fontSize: 34,
    fontWeight: '900',
    marginBottom: 4,
    textAlign: 'left',
  },
  streakNumberShell: {
    width: 92,
    minHeight: 92,
    borderRadius: 20,
    backgroundColor: '#FFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 4,
  },
  streakFire: { fontSize: 24 },
  streakNumber: { fontSize: 42, fontWeight: '900', color: NAVY },
  streakMetaColumn: {
    flex: 1,
    marginRight: 14,
    alignItems: 'center',
  },
  streakDays: {
    fontSize: 11,
    color: '#7A8594',
    fontWeight: '800',
    textAlign: 'center',
  },
  streakHint: {
    color: 'rgba(255,255,255,0.62)',
    fontSize: 12,
    lineHeight: 20,
    textAlign: 'left',
  },
  streakProgressWrap: {
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderRadius: 22,
    padding: 14,
    marginBottom: 16,
  },
  streakProgressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  streakProgressValue: {
    color: GOLD,
    fontSize: 13,
    fontWeight: '800',
  },
  streakProgressLabel: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 12,
    fontWeight: '700',
  },
  streakProgressTrack: {
    width: '100%',
    height: 8,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 999,
    overflow: 'hidden',
  },
  streakProgressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#78A1BD',
  },
  statsRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    justifyContent: 'space-between',
    width: '100%',
    gap: 8,
  },
  statBox: {
    alignItems: 'center',
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 8,
  },
  statNum: { fontSize: 18, fontWeight: '900', color: '#78A1BD' },
  statLabel: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.62)',
    marginTop: 4,
    textAlign: 'center',
    lineHeight: 16,
  },
  statDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#ddd',
  },
  badgesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  gallerySectionTitle: {
    color: NAVY,
    fontSize: 16,
    fontWeight: '900',
    marginBottom: 12,
    marginTop: 4,
    textAlign: 'left',
  },
  spotlightCard: {
    backgroundColor: '#FFF',
    borderRadius: 22,
    padding: 18,
    marginBottom: 18,
    overflow: 'hidden',
    shadowColor: '#0A1124',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 3,
  },
  spotlightGlow: {
    position: 'absolute',
    top: -20,
    right: -20,
    width: 140,
    height: 140,
    borderRadius: 70,
  },
  spotlightTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  spotlightPill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
  },
  spotlightPillText: {
    fontSize: 12,
    fontWeight: '800',
  },
  spotlightPillTextMuted: {
    color: '#667085',
  },
  spotlightIconWrap: {
    width: 50,
    height: 50,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  spotlightEmoji: {
    fontSize: 25,
  },
  spotlightTitle: {
    color: NAVY,
    fontSize: 24,
    fontWeight: '900',
    marginBottom: 4,
    textAlign: 'left',
  },
  spotlightDays: {
    color: '#7B8390',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'left',
  },
  spotlightMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  spotlightXp: {
    color: GOLD,
    fontSize: 12,
    fontWeight: '900',
    textAlign: 'left',
  },
  spotlightText: {
    color: '#445064',
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 14,
    textAlign: 'left',
  },
  spotlightProgressTrack: {
    width: '100%',
    height: 10,
    borderRadius: 999,
    backgroundColor: '#EEF2F6',
    overflow: 'hidden',
  },
  spotlightProgressFill: {
    height: '100%',
    borderRadius: 999,
  },
  badgeCard: {
    width: '48%',
    backgroundColor: '#FFF',
    borderRadius: 20,
    paddingVertical: 14,
    paddingHorizontal: 12,
    marginBottom: 14,
    alignItems: 'stretch',
    overflow: 'hidden',
    elevation: 3,
    shadowColor: '#0A1124',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
  },
  badgeSpacer: {
    width: '48%',
  },
  badgeCardEarned: {
    elevation: 3,
    shadowColor: '#78A1BD',
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  badgeCardLocked: {
    opacity: 0.84,
  },
  badgeCardAccent: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 5,
  },
  badgeTopRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  badgeIdentityRow: {
    position: 'relative',
    width: 54,
    height: 54,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeStatePill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  badgeStatePillEarned: {
    backgroundColor: 'rgba(120,161,189,0.12)',
  },
  badgeStatePillPending: {
    backgroundColor: '#F3F6FA',
  },
  badgeStateText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#6F7885',
    textAlign: 'center',
  },
  badgeDayChip: {
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  badgeChipColumn: {
    alignItems: 'flex-end',
    gap: 4,
    maxWidth: '62%',
  },
  badgeDayChipText: {
    fontSize: 10,
    fontWeight: '800',
    textAlign: 'center',
  },
  badgeXpText: {
    color: '#7B8491',
    fontSize: 10,
    fontWeight: '800',
    textAlign: 'right',
  },
  badgeRing: {
    width: 50,
    height: 50,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeEmoji: { fontSize: 27 },
  checkmark: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  badgeTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: NAVY,
    textAlign: 'left',
    marginBottom: 4,
  },
  badgeSubtitle: {
    fontSize: 11,
    color: '#7B8491',
    textAlign: 'left',
    lineHeight: 18,
    marginBottom: 10,
  },
  progressMetaRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  progressMetaText: {
    fontSize: 11,
    fontWeight: '800',
  },
  progressLabel: {
    fontSize: 11,
    color: '#8C95A1',
    fontWeight: '600',
  },
  progressBar: {
    width: '100%',
    height: 7,
    backgroundColor: '#EDF1F5',
    borderRadius: 999,
    overflow: 'hidden',
    marginBottom: 10,
  },
  progressFill: { height: '100%', borderRadius: 999 },
  earnedTag: {
    marginTop: 4,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    alignSelf: 'stretch',
  },
  earnedText: { fontSize: 12, fontWeight: '700', textAlign: 'center' },
  pendingRow: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    minHeight: 32,
  },
  pendingText: {
    fontSize: 11,
    color: '#7E8896',
    fontWeight: '700',
    textAlign: 'center',
  },
  motivationalCard: {
    backgroundColor: '#FFF',
    borderRadius: 20,
    marginBottom: 32,
    paddingVertical: 16,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#0A1124',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    gap: 12,
  },
  motivationalBody: { flex: 1, marginHorizontal: 12 },
  motivationalTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: NAVY,
    marginBottom: 4,
    textAlign: 'left',
  },
  motivationalText: {
    fontSize: 12,
    color: '#666',
    lineHeight: 18,
    textAlign: 'left',
  },
});
