export const authStrings = {
  common: {
    login: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    email: 'البريد الإلكتروني',
    emailPlaceholder: 'أدخل بريدك الإلكتروني',
    password: 'كلمة المرور',
    passwordPlaceholder: 'أدخل كلمة المرور',
    forgotPasswordQuestion: 'نسيت كلمه المرور ؟',
    playServicesUnavailable: 'خدمات Google Play غير متاحة أو قديمة.',
    genericErrorTitle: 'خطأ',
    cancelledTitle: 'تم الإلغاء',
    signInInProgressTitle: 'جاري تسجيل الدخول',
    signUpInProgressTitle: 'جاري التسجيل',
    inProgressMessage: 'العملية جارية بالفعل.',
    secureHint: 'دخول آمن ومشفّر',
    or: 'أو',
    next: 'التالي',
    rememberMe: 'ذكرني',
  },
  login: {
    title: 'تسجيل الدخول',
    emailRequired: 'يرجى إدخال البريد الإلكتروني',
    emailInvalid: 'يرجى إدخال بريد إلكتروني صحيح',
    passwordRequired: 'يرجى إدخال كلمة المرور',
    signInErrorTitle: 'خطأ في تسجيل الدخول',
    cancelledMessage: 'تم إلغاء عملية تسجيل الدخول.',
    inProgressMessage: 'عملية تسجيل الدخول جارية بالفعل.',
    googleButton: 'تسجيل الدخول باستخدام جوجل',
    facebookButton: 'تسجيل الدخول باستخدام فيسبوك',
    footerPrefix: 'ليس لديك حساب؟ ',
    footerAction: 'إنشاء حساب جديد',
  },
  signup: {
    title: 'إنشاء حساب',
    fullName: 'الاسم الكامل',
    fullNamePlaceholder: 'أدخل اسمك',
    phone: 'رقم الهاتف',
    phonePlaceholder: 'أدخل رقم هاتفك',
    passwordPlaceholder: '8 أحرف على الأقل',
    confirmPassword: 'تأكيد كلمة المرور',
    confirmPasswordPlaceholder: 'أعد إدخال كلمة المرور',
    fullNameRequired: 'يرجى إدخال الاسم الكامل',
    emailRequired: 'يرجى إدخال البريد الإلكتروني',
    emailInvalid: 'يرجى إدخال بريد إلكتروني صحيح',
    phoneRequired: 'يرجى إدخال رقم الهاتف',
    phoneInvalid: 'يرجى إدخال رقم هاتف صحيح',
    passwordRequired: 'يرجى إدخال كلمة المرور',
    passwordTooShort: (min: number) =>
      `كلمة المرور يجب أن تكون ${min} أحرف على الأقل`,
    confirmPasswordRequired: 'يرجى تأكيد كلمة المرور',
    confirmPasswordMismatch: 'كلمة المرور غير متطابقة',
    signUpErrorTitle: 'خطأ في التسجيل',
    cancelledMessage: 'تم إلغاء عملية التسجيل.',
    inProgressMessage: 'عملية التسجيل جارية بالفعل.',
    googleButton: 'إنشاء حساب باستخدام جوجل',
    facebookButton: 'إنشاء حساب باستخدام فيسبوك',
    footerPrefix: 'لديك حساب بالفعل؟ ',
    footerAction: 'تسجيل الدخول',
  },
  forgotPassword: {
    title: 'نسيت كلمة المرور؟',
    emailRequired: 'يرجى إدخال البريد الإلكتروني',
    emailInvalid: 'يرجى إدخال بريد إلكتروني صحيح',
    resetSentTitle: 'تحقق من بريدك!',
    resetSentMessage: 'لقد أرسلنا رابط إعادة تعيين كلمة المرور إلى:',
    resetHint: 'إذا لم تجد الرسالة، تحقق من مجلد الرسائل غير المرغوب فيها.',
    resend: 'إرسال مرة أخرى',
    sendRecoveryLink: 'إرسال رابط الاستعادة',
    footerPrefix: 'تذكرت كلمة المرور؟ ',
    footerAction: 'تسجيل الدخول',
    infoTitle: 'استعادة سريعة وآمنة',
    infoDescription:
      'أدخل بريدك الإلكتروني لنرسل لك رابطًا يعيدك مباشرة إلى حسابك.',
  },
  resetPassword: {
    invalidLinkTitle: 'رابط غير صالح',
    requestSentTitle: 'تم الإرسال!',
    newPasswordTitle: 'تعيين كلمة مرور جديدة',
    newPasswordRequired: 'يرجى إدخال كلمة المرور الجديدة',
    confirmPasswordRequired: 'يرجى تأكيد كلمة المرور',
    confirmPasswordMismatch: 'كلمتا المرور غير متطابقتين',
    passwordTooShort: (min: number) =>
      `كلمة المرور يجب أن تكون ${min} أحرف على الأقل`,
    invalidDataTitle: 'تحقق من البيانات',
    successTitle: 'تم بنجاح! 🎉',
    successMessage:
      'تم تغيير كلمة مرورك بنجاح. يمكنك الآن تسجيل الدخول باستخدامها.',
    requestEmailRequired: 'يرجى إدخال البريد الإلكتروني',
    requestEmailInvalid: 'يرجى إدخال بريد إلكتروني صحيح',
    linkOffMessage:
      'رابط إعادة تعيين كلمة المرور غير صالح أو منتهي الصلاحية.\nأدخل بريدك الإلكتروني لإرسال رابط جديد.',
    requestNewLinkTitle: 'أدخل بريدك الإلكتروني لإرسال رابط استعادة جديد.',
    newPasswordSubtitle: 'أدخل كلمة المرور الجديدة وأكدها.',
    requestSentSubtitle: 'تم إرسال رابط جديد إلى بريدك الإلكتروني.',
    requestSentCheckTitle: 'تحقق من بريدك!',
    requestSentCheckMessage: 'لقد أرسلنا رابط إعادة تعيين كلمة المرور إلى:',
    requestSentHint:
      'إذا لم تجد الرسالة، تحقق من مجلد الرسائل غير المرغوب فيها.',
    resend: 'إرسال مرة أخرى',
    sendNewLink: 'إرسال رابط جديد',
    newPassword: 'كلمة المرور الجديدة',
    confirmPassword: 'تأكيد كلمة المرور',
    minPasswordHint: (min: number) =>
      `كلمة المرور يجب أن تكون ${min} أحرف على الأقل`,
    submit: 'تعيين كلمة المرور',
    infoTitle: 'أنشئ كلمة مرور قوية',
    infoDescription:
      'اختر كلمة مرور جديدة يسهل عليك تذكرها ويصعب على غيرك توقعها.',
    footerPrefix: 'تذكرت كلمة المرور؟ ',
    footerAction: 'تسجيل الدخول',
  },
  profileCompletion: {
    title: 'إكمال الملف الشخصي',
    requiresLoginTitle: 'لازم تسجل دخول الأول',
    requiresLoginMessage:
      'إكمال الملف الشخصي يحتاج جلسة تسجيل دخول فعالة. أكّد بريدك الإلكتروني ثم سجّل الدخول مرة أخرى.',
    churchSection: 'معلومات الكنيسة',
    church: 'الكنيسة',
    churchPlaceholder: 'اسم الكنيسة',
    sect: 'الطائفة',
    sectPlaceholder: 'اسم الطائفة',
    personalSection: 'معلومات شخصية',
    birthDate: 'تاريخ الميلاد',
    birthDatePlaceholder: 'اضغط لاختيار التاريخ',
    datePickerTitle: 'تاريخ الميلاد',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    gender: 'الجنس',
    male: 'ذكر',
    female: 'أنثى',
    optional: 'اختياري',
    submit: 'إنشاء الحساب',
    requiresLoginNotice: (email?: string) =>
      email
        ? `تم إنشاء الحساب للبريد ${email}. أكّد البريد الإلكتروني أولًا، ثم سجّل الدخول لحفظ الملف الشخصي.`
        : 'تم إنشاء الحساب. أكّد البريد الإلكتروني أولًا، ثم سجّل الدخول لحفظ الملف الشخصي.',
  },
} as const;
