export const bibleMemorizationStrings = {
  difficultyLevels: {
    easy: 'سهل',
    medium: 'متوسط',
    hard: 'صعب',
    fullText: 'كتابة كاملة',
  },
  tabs: {
    pick: 'اختيار التسميع',
    stats: 'الإحصائيات',
  },
  pick: {
    title: 'حفظ الكتاب المقدس',
    pickerTitles: {
      chapter: 'اختر الإصحاح',
      singleVerse: 'اختر العدد',
      fromVerse: 'من عدد',
      toVerse: 'إلى عدد',
    },
    alerts: {
      title: 'تنبيه',
      selectBookAndChapter: 'اختر السفر والإصحاح أولاً.',
      invalidVerseRange: 'آخر عدد يجب أن يكون بعد أول عدد.',
      versesNotFound: 'لم يتم العثور على الأعداد المطلوبة.',
    },
    chapterLabelSingle: (chapter: number, start: number) =>
      `إصحاح ${chapter}، عدد ${start}`,
    chapterLabelRange: (chapter: number, start: number, end: number) =>
      `إصحاح ${chapter}، الأعداد ${start}-${end}`,
    heroBadge: 'يلا نحفظ',
    heroEyebrow: 'ابدأ من هنا',
    heroTitle: 'اختر الجزء الذي تريد حفظه',
    heroText: 'حدّد السفر والإصحاح والأعداد، ثم اختر مستوى التحدي المناسب لك.',
    chooseBook: 'اختر السفر',
    chooseBookCaption: 'تنقّل بين أسفار العهدين واختر الجزء المناسب.',
    oldTestament: 'العهد القديم',
    newTestament: 'العهد الجديد',
    oldTestamentBooks: 'أسفار العهد القديم',
    newTestamentBooks: 'أسفار العهد الجديد',
    sliderHint: 'اسحب يمينًا ويسارًا للتنقل بين الأسفار',
    choosePlace: 'اختر المكان',
    choosePlaceCaption: 'حدّد الإصحاح والعدد أو مدى الأعداد التي تريد تسميعها.',
    chapter: 'الإصحاح',
    chapterValue: (chapter: number) => `إصحاح ${chapter}`,
    selectionType: 'نوع التحديد',
    singleVerse: 'عدد واحد',
    rangeVerse: 'كذا عدد',
    verse: 'العدد',
    fromVerse: 'من عدد',
    toVerse: 'إلى عدد',
    selectAllVerses: 'اختيار كل الأعداد',
    clearVerses: 'إلغاء اختيار كل الأعداد',
    verseValue: (value: number) => `عدد ${value}`,
    levelTitle: 'مستوى الحفظ',
    levelCaption: 'اختر إخفاء كلمات أو اكتب الآية كاملة ثم راجع أخطاءك.',
    easyHint: 'سيتم إخفاء كلمات قليلة لتبدأ بسهولة.',
    mediumHint: 'سيتم إخفاء عدد متوسط من الكلمات.',
    hardHint: 'سيتم إخفاء عدد أكبر من الكلمات لتحدي أقوى.',
    fullTextHint: 'اكتب الآية كاملة من حفظك، وسيظهر لك الخطأ في كل كلمة.',
    start: 'ابدأ التسميع',
    stats: {
      weeklyProgress: 'تقدمك الأسبوعي',
      monthlyProgress: 'تقدمك الشهري',
      versesMemorized: 'آية تم حفظها',
      totalVerses: 'إجمالي الآيات الصحيحة',
      totalAttempts: 'عدد المحاولات',
      avgScore: 'متوسط النتيجة',
      currentPeriod: 'الفترة الحالية',
      goalReach: (current: number, goal: number) =>
        `حفظت صح ${current} من هدفك (${goal} آيات)`,
      setGoal: 'تحديد الهدف',
      goalModalTitle: 'حدد هدف الحفظ',
      goalModalCaption: 'اختر هدفك وعدد الآيات والفترة المناسبة.',
      periodWeek: 'أسبوعي',
      periodMonth: 'شهري',
      versesUnit: 'آيات',
      currentStreak: 'أيام متتالية',
      avgTime: 'متوسط الوقت',
      perfectAttempts: 'محاولات كاملة',
      bestScore: 'أفضل نتيجة',
      difficultyBreakdown: 'حسب مستوى الحفظ',
      deleteHistoryItem: 'حذف النتيجة',
      saveGoal: 'حفظ الهدف',
    },
  },
  recite: {
    title: 'التسميع',
    instruction: 'أكمل الكلمات المحجوبة في النص التالي:',
    fullTextInstruction: 'اكتب الآية كاملة من حفظك في المساحة التالية:',
    blanks: (count: number) => `${count} فراغ`,
    fullTextWords: (count: number) => `${count} كلمة للمراجعة`,
    referenceTextTitle: 'نص المراجعة',
    verseTextTitle: 'نص التسميع',
    answerTitle: 'اكتب الآية',
    showResult: 'عرض النتيجة',
    chooseAnotherReference: 'اختر جزءًا آخر للحفظ',
    blankPlaceholder: '___',
    fullTextPlaceholder: 'اكتب الآية هنا...',
    showReferenceText: 'إظهار النص',
    hideReferenceText: 'إخفاء النص',
  },
  result: {
    title: 'النتيجة',
    badge: 'نتيجتك النهارده',
    scoreLabel: 'النتيجة',
    hiddenWordsLabel: 'الكلمات للمراجعة',
    correctWordsLabel: 'الإجابات الصح',
    verseReferenceLabel: 'الجزء اللي حفظته',
    perfect: 'ممتاز! حفظت النص بشكل كامل!',
    good: 'جيد جداً، حاول مرة أخرى لتثبيت الحفظ.',
    retry: 'راجع النص وحاول مرة أخرى.',
    perfectBadge: 'إتقان كامل',
    goodBadge: 'مستوى جيد جدًا',
    retryBadge: 'يحتاج مراجعة',
    instruction: 'الكلمات الصحيحة تظهر بوضوح، والخطأ يظهر مع الإجابة الأصلية.',
    reviewAnswers: 'مراجعة الإجابات',
    writtenReviewAnswers: 'مراجعة كلمات الآية',
    retryAction: 'حاول مرة أخرى',
    chooseAnotherReference: 'اختر جزءًا آخر للحفظ',
    backToHome: 'الرجوع للرئيسية',
    wrongAnswerFallback: '؟',
    timeTaken: (seconds: number) => `الوقت: ${seconds} ثانية`,
  },
  stats: {
    weeklyProgress: 'تقدمك الأسبوعي',
    monthlyProgress: 'تقدمك الشهري',
    versesMemorized: 'آية تم حفظها',
    totalVerses: 'إجمالي الآيات الصحيحة',
    totalAttempts: 'عدد المحاولات',
    avgScore: 'متوسط النتيجة',
    currentPeriod: 'الفترة الحالية',
    goalReach: (current: number, goal: number) =>
      `حفظت صح ${current} من هدفك (${goal} آيات)`,
    setGoal: 'تحديد الهدف',
    goalModalTitle: 'حدد هدف الحفظ',
    goalModalCaption: 'اختر هدفك وعدد الآيات والفترة المناسبة.',
    periodWeek: 'أسبوعي',
    periodMonth: 'شهري',
    versesUnit: 'آيات',
    currentStreak: 'أيام متتالية',
    avgTime: 'متوسط الوقت',
    perfectAttempts: 'محاولات كاملة',
    bestScore: 'أفضل نتيجة',
    difficultyBreakdown: 'حسب مستوى الحفظ',
    deleteHistoryItem: 'حذف النتيجة',
    saveGoal: 'حفظ الهدف',
  },
} as const;
