export const bibleMemorizationStrings = {
  difficultyLevels: {
    easy: 'سهل',
    medium: 'متوسط',
    hard: 'صعب',
  },
  pick: {
    title: 'حفظ الكتاب المقدس',
    pickerTitles: {
      chapter: 'اختر الإصحاح',
      singleVerse: 'اختر العدد',
      fromVerse: 'من عدد',
      toVerse: 'إلى عدد',
    },
    alerts: {
      title: 'تنبيه',
      selectBookAndChapter: 'اختر السفر والإصحاح أولاً.',
      invalidVerseRange: 'آخر عدد يجب أن يكون بعد أول عدد.',
      versesNotFound: 'لم يتم العثور على الأعداد المطلوبة.',
    },
    chapterLabelSingle: (chapter: number, start: number) =>
      `إصحاح ${chapter}، عدد ${start}`,
    chapterLabelRange: (chapter: number, start: number, end: number) =>
      `إصحاح ${chapter}، الأعداد ${start}-${end}`,
    heroBadge: 'يلا نحفظ',
    heroEyebrow: 'ابدأ من هنا',
    heroTitle: 'اختر الجزء الذي تريد حفظه',
    heroText: 'حدّد السفر والإصحاح والأعداد، ثم اختر مستوى التحدي المناسب لك.',
    chooseBook: 'اختر السفر',
    chooseBookCaption: 'تنقّل بين أسفار العهدين واختر الجزء المناسب.',
    oldTestament: 'العهد القديم',
    newTestament: 'العهد الجديد',
    oldTestamentBooks: 'أسفار العهد القديم',
    newTestamentBooks: 'أسفار العهد الجديد',
    sliderHint: 'اسحب يمينًا ويسارًا للتنقل بين الأسفار',
    choosePlace: 'اختر المكان',
    choosePlaceCaption: 'حدّد الإصحاح والعدد أو مدى الأعداد التي تريد تسميعها.',
    chapter: 'الإصحاح',
    chapterValue: (chapter: number) => `إصحاح ${chapter}`,
    selectionType: 'نوع التحديد',
    singleVerse: 'عدد واحد',
    rangeVerse: 'كذا عدد',
    verse: 'العدد',
    fromVerse: 'من عدد',
    toVerse: 'إلى عدد',
    verseValue: (value: number) => `عدد ${value}`,
    levelTitle: 'مستوى الحفظ',
    levelCaption: 'كل مستوى يغيّر عدد الكلمات المخفية أثناء التسميع.',
    easyHint: 'سيتم إخفاء كلمات قليلة لتبدأ بسهولة.',
    mediumHint: 'سيتم إخفاء عدد متوسط من الكلمات.',
    hardHint: 'سيتم إخفاء عدد أكبر من الكلمات لتحدي أقوى.',
    start: 'ابدأ التسميع',
  },
  recite: {
    title: 'التسميع',
    instruction: 'أكمل الكلمات المحجوبة في النص التالي:',
    blanks: (count: number) => `${count} فراغ`,
    verseTextTitle: 'نص التسميع',
    showResult: 'عرض النتيجة',
    chooseAnotherReference: 'اختر جزءًا آخر للحفظ',
    blankPlaceholder: '___',
  },
  result: {
    title: 'النتيجة',
    badge: 'نتيجتك النهارده',
    scoreLabel: 'النتيجة',
    hiddenWordsLabel: 'الكلمات المخفية',
    correctWordsLabel: 'الإجابات الصح',
    verseReferenceLabel: 'الجزء اللي حفظته',
    perfect: 'ممتاز! حفظت النص بشكل كامل!',
    good: 'جيد جداً، حاول مرة أخرى لتثبيت الحفظ.',
    retry: 'راجع النص وحاول مرة أخرى.',
    perfectBadge: 'إتقان كامل',
    goodBadge: 'مستوى جيد جدًا',
    retryBadge: 'يحتاج مراجعة',
    instruction: 'الكلمات الصحيحة تظهر بوضوح، والخطأ يظهر مع الإجابة الأصلية.',
    reviewAnswers: 'مراجعة الإجابات',
    retryAction: 'حاول مرة أخرى',
    chooseAnotherReference: 'اختر جزءًا آخر للحفظ',
    wrongAnswerFallback: '؟',
  },
} as const;
