export const dailyNotificationsStrings = {
  tips: [
    'اختر وقتاً هادئاً في الصباح الباكر قبل بداية اليوم.',
    'اختر مكاناً هادئاً بعيداً عن الضوضاء والمشتتات.',
    'ابدأ بقراءة الكتاب المقدس ثم الصلاة والتأمل.',
    'أبعد هاتفك أثناء وقتك مع الله وركّز على الحضور الإلهي.',
    'حتى 15 دقيقة يومياً كافية للبدء، الاستمرارية هي المفتاح.',
  ],
  saveErrorTitle: 'خطأ في الحفظ',
  saveSuccessTitle: 'تم الحفظ ✅',
  saveSuccessMessage: (timeString: string) =>
    `تم حفظ وقتك مع الله: ${timeString}\nهنبعتلك تذكير كل يوم عشان ماتفوتش وقتك مع الله 🙏`,
  saveOfflineMessage: (timeString: string) =>
    `تم حفظ الإعدادات محلياً: ${timeString}\nوسيتم رفعها إلى حسابك تلقائياً عند عودة الإنترنت.`,
  scheduleErrorTitle: 'التذكير لم يتفعل',
  scheduleErrorMessage:
    'تم حفظ الإعدادات، لكن لم نقدر نجهز التذكير على الجهاز. جرّب تفعيل الإشعارات مرة أخرى.',
  saved: 'تم الحفظ',
  readyToSave: 'جاهز للحفظ',
  morning: 'بداية اليوم',
  evening: 'موعد مسائي',
  title: 'وقتك مع الله كل يوم',
  badge: 'تذكير يومي',
  heroTitle: 'خصص لحظة ثابتة كل يوم لوقت هادئ مع الله',
  heroSubtitle:
    'اختر التوقيت الأنسب لك، وسنذكّرك يوميًا حتى يبقى وقتك مع الله جزءًا ثابتًا من يومك.',
  selectedTime: 'الوقت المختار',
  editTime: 'تعديل الموعد',
  editTimeSubtitle: 'حرّك المؤشر لاختيار الوقت المناسب',
  readingPlanTitle: 'خطة القراءة اليومية',
  readingPlanSubtitle: 'حدد المكان اللي هتبدأ منه والقراءات اليومية',
  suggestionsTitle: 'اقتراحات جاهزة',
  suggestionsSubtitle:
    'افتح شاشة الخطط الجاهزة واختار منها اللي يناسبك.',
  openSuggestions: 'اختيار خطة قراءة',
  suggestionsScreenTitle: 'اقتراحات القراءة',
  suggestionsScreenHeading: 'اختار بداية مناسبة لرحلتك',
  suggestionsScreenBody:
    'كل خطة هتجهز قراءة اليوم تلقائياً. بعد الاختيار هترجع تعدّل أو تحفظ من شاشة وقتك مع الله.',
  applySuggestion: 'استخدام الخطة',
  suggestionEntriesCount: (count: number) =>
    count === 1 ? 'قراءة واحدة لليوم' : `${count} قراءات لليوم`,
  suggestionDaysCount: (count: number) =>
    count === 1 ? 'يوم واحد' : `${count} يوم`,
  suggestionDayLabel: (day: number) => `اليوم ${day}`,
  suggestionMoreDays: (count: number) => `+ ${count} يوم آخر في الخطة`,
  showAllDays: 'عرض كل الأيام',
  hidePlanDays: 'إخفاء باقي الأيام',
  readingPlanSuggestions: {
    bibleYearTitle: 'الكتاب كله في سنة',
    bibleYearSubtitle: 'ابدأ من التكوين بقراءة يومية متوازنة حوالي 4 إصحاحات.',
    bibleYearBadge: '365 يوم',
    newTestamentTitle: 'العهد الجديد في 3 شهور',
    newTestamentSubtitle: 'رحلة مركّزة تبدأ من إنجيل متى حوالي 3 إصحاحات يومياً.',
    newTestamentBadge: '90 يوم',
    topicalPeaceTitle: 'سلام وتشجيع',
    topicalPeaceSubtitle: 'قراءات مختارة من المزامير ويوحنا وفيلبي لوقت هادئ.',
    topicalPeaceBadge: 'موضوعية',
    topicalWisdomTitle: 'حكمة عملية',
    topicalWisdomSubtitle: 'بداية قصيرة من الأمثال ويعقوب للقرارات اليومية.',
    topicalWisdomBadge: 'موضوعية',
    paceTitle: 'حسب سرعتك الحالية',
    paceSubtitle: (chapters: number) =>
      `اقتراح تلقائي يكمل من آخر قراءة بمعدل ${chapters} إصحاح يومياً.`,
    paceBadge: 'تلقائي',
  },
  multipleReadingsHint:
    'تقدر تضيف أكتر من قراءة في خطتك. اختار السفر والإصحاحات، واضغط إضافة قراءة أخرى.',
  addReadingEntry: 'إضافة قراءة أخرى',
  removeReadingEntry: 'حذف',
  selectBook: 'اختار السفر',
  selectBookFirst: 'اختار السفر الأول',
  oldTestament: 'العهد القديم',
  newTestament: 'العهد الجديد',
  selectChapter: 'الإصحاحات',
  chapterRangeHint: 'اختار أي إصحاحات حابب تقراها، ومش لازم يكونوا ورا بعض.',
  selectAllChapters: 'اختيار كل الإصحاحات',
  readingSelectionRequiredTitle: 'اختيار القراءة مطلوب',
  readingSelectionRequiredMessage:
    'لازم تختار سفر وإصحاح واحد على الأقل قبل الحفظ.',
  chapterRangeSummarySingle: 'الإصحاح المختار',
  chapterRangeSummary: 'الجزء اليومي المختار',
  saveTime: 'حفظ الوقت',
  permissionNoticeTitle: 'التذكير اليومي غير مفعّل',
  permissionNoticeBody:
    'فعّله علشان التذكير يوصلك في وقته كل يوم، أو افتح الإعدادات لو كنت قافله قبل كده.',
  permissionEnable: 'تفعيل الإشعارات',
  permissionOpenSettings: 'فتح الإعدادات',
  tipsTitle: 'نصائح لوقت هادئ مع الله',
  tipsSubtitle: 'خطوات صغيرة تساعدك على الاستمرار كل يوم',
} as const;
