export const dailyNotificationsStrings = {
  tips: [
    'اختر وقتاً هادئاً في الصباح الباكر قبل بداية اليوم.',
    'اختر مكاناً هادئاً بعيداً عن الضوضاء والمشتتات.',
    'ابدأ بقراءة الكتاب المقدس ثم الصلاة والتأمل.',
    'أبعد هاتفك أثناء وقت التعبد وركّز على الحضور الإلهي.',
    'حتى 15 دقيقة يومياً كافية للبدء، الاستمرارية هي المفتاح.',
  ],
  saveErrorTitle: 'خطأ في الحفظ',
  saveSuccessTitle: 'تم الحفظ ✅',
  saveSuccessMessage: (timeString: string) =>
    `تم حفظ وقت تعبّدك: ${timeString}\nهنبعتلك تذكير كل يوم عشان ماتفوتش وقتك مع الله 🙏`,
  saved: 'تم الحفظ',
  readyToSave: 'جاهز للحفظ',
  morning: 'بداية اليوم',
  evening: 'موعد مسائي',
  title: 'وقت التعبد اليومي',
  badge: 'تذكير يومي',
  heroTitle: 'خصص لحظة ثابتة كل يوم لوقت هادئ مع الله',
  heroSubtitle:
    'اختر التوقيت الأنسب لك، وسنذكّرك يوميًا حتى يبقى وقت التعبد جزءًا ثابتًا من يومك.',
  selectedTime: 'الوقت المختار',
  editTime: 'تعديل الموعد',
  editTimeSubtitle: 'حرّك المؤشر لاختيار الوقت المناسب',
  readingPlanTitle: 'خطة القراءة اليومية',
  readingPlanSubtitle: 'حدد المكان اللي هتبدأ منه وكمية القراءة كل يوم',
  selectBook: 'اختار السفر',
  oldTestament: 'العهد القديم',
  newTestament: 'العهد الجديد',
  selectChapter: 'اختار الإصحاح',
  chaptersPerDay: 'عدد الإصحاحات يومياً',
  saveTime: 'حفظ الوقت',
  tipsTitle: 'نصائح للتعبد الفعّال',
  tipsSubtitle: 'خطوات صغيرة تساعدك على الاستمرار كل يوم',
} as const;
