export const dailyNotificationsStrings = {
  tips: [
    'اختر وقتاً هادئاً في الصباح الباكر قبل بداية اليوم.',
    'اختر مكاناً هادئاً بعيداً عن الضوضاء والمشتتات.',
    'ابدأ بقراءة الكتاب المقدس ثم الصلاة والتأمل.',
    'أبعد هاتفك أثناء وقتك مع الله وركّز على الحضور الإلهي.',
    'حتى 15 دقيقة يومياً كافية للبدء، الاستمرارية هي المفتاح.',
  ],
  saveErrorTitle: 'خطأ في الحفظ',
  saveSuccessTitle: 'تم الحفظ ✅',
  saveSuccessMessage: (timeString: string) =>
    `تم حفظ وقتك مع الله: ${timeString}\nهنبعتلك تذكير كل يوم عشان ماتفوتش وقتك مع الله 🙏`,
  saveOfflineMessage: (timeString: string) =>
    `تم حفظ الإعدادات محلياً: ${timeString}\nوسيتم رفعها إلى حسابك تلقائياً عند عودة الإنترنت.`,
  saved: 'تم الحفظ',
  readyToSave: 'جاهز للحفظ',
  morning: 'بداية اليوم',
  evening: 'موعد مسائي',
  title: 'وقتك مع الله كل يوم',
  badge: 'تذكير يومي',
  heroTitle: 'خصص لحظة ثابتة كل يوم لوقت هادئ مع الله',
  heroSubtitle:
    'اختر التوقيت الأنسب لك، وسنذكّرك يوميًا حتى يبقى وقتك مع الله جزءًا ثابتًا من يومك.',
  selectedTime: 'الوقت المختار',
  editTime: 'تعديل الموعد',
  editTimeSubtitle: 'حرّك المؤشر لاختيار الوقت المناسب',
  readingPlanTitle: 'خطة القراءة اليومية',
  readingPlanSubtitle: 'حدد المكان اللي هتبدأ منه وكمية القراءة كل يوم',
  selectBook: 'اختار السفر',
  selectBookFirst: 'اختار السفر الأول',
  oldTestament: 'العهد القديم',
  newTestament: 'العهد الجديد',
  selectChapter: 'الإصحاحات',
  chapterRangeHint: 'اختار أي إصحاحات حابب تقراها، ومش لازم يكونوا ورا بعض.',
  selectAllChapters: 'اختيار كل الإصحاحات',
  readingSelectionRequiredTitle: 'اختيار القراءة مطلوب',
  readingSelectionRequiredMessage: 'لازم تختار سفر وإصحاح واحد على الأقل قبل الحفظ.',
  chapterRangeSummarySingle: 'الإصحاح المختار',
  chapterRangeSummary: 'الجزء اليومي المختار',
  saveTime: 'حفظ الوقت',
  permissionNoticeTitle: 'التذكير اليومي غير مفعّل',
  permissionNoticeBody:
    'فعّله علشان التذكير يوصلك في وقته كل يوم، أو افتح الإعدادات لو كنت قافله قبل كده.',
  permissionEnable: 'تفعيل الإشعارات',
  permissionOpenSettings: 'فتح الإعدادات',
  tipsTitle: 'نصائح لوقت هادئ مع الله',
  tipsSubtitle: 'خطوات صغيرة تساعدك على الاستمرار كل يوم',
} as const;
