export const devotionCalendarStrings = {
  weekDays: ['س', 'ح', 'ن', 'ث', 'ر', 'خ', 'ج'],
  errorTitle: 'خطأ',
  title: 'متابعة وقتك مع الله',
  badge: 'ثبات يومي',
  heroLabel: 'متابعة وقتك مع الله',
  heroTitle: 'كل يوم "نعم" يترك أثرًا هنا',
  heroText:
    'التقويم يوضح أيام التزامك بالخلوة، ويساعدك ترى الاستمرارية بشكل بصري وواضح.',
  heroHint: 'الأيام الذهبية تعني أنك أكملت الخلوة في هذا اليوم',
  currentStreak: 'الثبات الحالي',
  thisMonth: 'هذا الشهر',
  total: 'الإجمالي',
  sectionTitle: 'تقويم الالتزام',
  sectionCaption: 'تنقّل بين الشهور وشاهد الأيام المكتملة',
  selectedDayTitle: 'تفاصيل اليوم',
  noRecordForDay: 'مفيش تسجيل خلوة في اليوم ده.',
  noRecordStatus: 'غير مسجل',
  notCompleted: 'لم تكتمل',
  noReadingDetails: 'بدون تفاصيل قراءة',
  recordDevotion: 'تسجيل خلوة',
  trackDayTitle: 'تسجيل يوم محدد',
  trackDaySubtitle: 'اختار يوم من التقويم وحدد هل أخدت الخلوة والقراءات.',
  multipleReadingsHint:
    'تقدر تضيف أكتر من قراءة في نفس اليوم، مثل: متى ٥، ٦ والمزامير ١، ٢.',
  addReadingEntry: 'إضافة قراءة أخرى',
  removeReadingEntry: 'حذف',
  pickedDate: 'اليوم المختار',
  answerQuestion: 'هل أخدت الخلوة في اليوم ده؟',
  yes: 'نعم ✓',
  no: 'لا ✗',
  selectBook: 'قريت في سفر إيه؟',
  selectBookFirst: 'اختار السفر الأول',
  oldTestament: 'العهد القديم',
  newTestament: 'العهد الجديد',
  selectChapter: 'الإصحاحات',
  chapterRangeHint: 'اختار أي إصحاحات حابب تقراها، ومش لازم يكونوا ورا بعض.',
  selectAllChapters: 'اختيار كل الإصحاحات',
  readingSelectionRequiredTitle: 'اختيار القراءة مطلوب',
  readingSelectionRequiredMessage: 'لازم تختار سفر وإصحاح واحد على الأقل قبل الحفظ.',
  chapterRangeSummarySingle: 'الإصحاح المختار',
  chapterRangeSummary: 'الجزء المختار',
  saveDay: 'حفظ اليوم',
  closeEditor: 'إغلاق',
  futureDateTitle: 'تاريخ مستقبلي',
  futureDateMessage: 'اختار يوم اليوم أو قبله عشان تسجل الخلوة.',
  saveSuccessTitle: 'تم الحفظ ✅',
  saveSuccessMessage: 'تم تحديث حالة اليوم بنجاح.',
  savedOfflineMessage:
    'تم حفظ اليوم على الجهاز، وسيتم رفعه إلى الحساب تلقائياً عند عودة الإنترنت.',
  completed: 'مكتمل',
  today: 'اليوم',
  remainingDays: 'باقي الأيام',
} as const;
