export const devotionCalendarStrings = {
  weekDays: ['س', 'ح', 'ن', 'ث', 'ر', 'خ', 'ج'],
  errorTitle: 'خطأ',
  title: 'متابعة وقتك مع الله',
  badge: 'ثبات يومي',
  heroLabel: 'متابعة وقتك مع الله',
  heroTitle: 'كل يوم "نعم" يترك أثرًا هنا',
  heroText:
    'التقويم يوضح أيام التزامك بالخلوة، ويساعدك ترى الاستمرارية بشكل بصري وواضح.',
  heroHint: 'الأيام الذهبية تعني أنك أكملت الخلوة في هذا اليوم',
  currentStreak: 'الثبات الحالي',
  thisMonth: 'هذا الشهر',
  total: 'الإجمالي',
  sectionTitle: 'تقويم الالتزام',
  sectionCaption: 'تنقّل بين الشهور وشاهد الأيام المكتملة',
  trackDayTitle: 'تسجيل يوم محدد',
  trackDaySubtitle: 'اختار يوم من التقويم وحدد هل أخدت الخلوة.',
  pickedDate: 'اليوم المختار',
  answerQuestion: 'هل أخدت الخلوة في اليوم ده؟',
  yes: 'نعم ✓',
  no: 'لا ✗',
  selectBook: 'قريت في سفر إيه؟',
  oldTestament: 'العهد القديم',
  newTestament: 'العهد الجديد',
  selectChapter: 'الإصحاحات',
  chapterRangeHint: 'اختار أي إصحاحات حابب تقراها، ومش لازم يكونوا ورا بعض.',
  chapterRangeSummarySingle: 'الإصحاح المختار',
  chapterRangeSummary: 'الجزء المختار',
  saveDay: 'حفظ اليوم',
  closeEditor: 'إغلاق',
  futureDateTitle: 'تاريخ مستقبلي',
  futureDateMessage: 'اختار يوم اليوم أو قبله عشان تسجل الخلوة.',
  saveSuccessTitle: 'تم الحفظ ✅',
  saveSuccessMessage: 'تم تحديث حالة اليوم بنجاح.',
  completed: 'مكتمل',
  today: 'اليوم',
  remainingDays: 'باقي الأيام',
} as const;
