export const homeStrings = {
  dailyQuestion: 'هل خدت وقت تقرأ في الكتاب المقدس وتقعد مع ربنا النهارده؟',
  yesMessage:
    'كمل كده، خليك ثابت في وقتك مع ربنا كل يوم\n"أَقِيمُوا فِيَّ وَأَنَا فِيكُمْ" يوحنا ١٥:٤',
  noMessage:
    '  لا يزال الوقت أمامك اليوم\nحتى ١٠ دقائق هادئة مع الله تغيّر يومك بالكامل',
  logoutTitle: 'تسجيل الخروج',
  logoutMessage: 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
  cancel: 'إلغاء',
  logout: 'خروج',
  correctStreakTitle: 'حلو جدًا 👏💪، وقتك مع ربنا غالي 🙏',
  startNowTitle: 'لا بأس 💙',
  startNowAction: 'ابدأ خلوتي الآن',
  later: 'حسنا',
  answerPrompt: 'قضيت وقتاً مع الله اليوم؟',
  yes: 'نعم ✓',
  no: 'لا ✗',
  featurePrayerNotesTitle: 'طلبات الصلاة',
  featurePrayerNotesSubtitle: 'شارك صلواتك وطلباتك',
  featureCalendarTitle: 'متابعة وقتك مع الله',
  featureCalendarSubtitle: 'راجع أيام التزامك وافتح التقويم الكامل',
  featureReflectionTitle: 'اليوميات',
  featureReflectionSubtitle: 'سجل خواطرك اليومية',
  headerEyebrow: 'وقت مع ربنا',
  headerSubGreeting: 'جاهز لوقتك مع الله النهاردة؟',
  headerCaption: 'ابدأ يومك مع ربنا وخليه أول حاجة في يومك',
  dailyCardLabel: 'سؤال اليوم المتغير',
  answerNow: 'جاوب الآن',
  editAnswer: 'تعديل الإجابة',
  answeredYes: 'حلو جدًا 👏💪، وقتك مع ربنا غالي 🙏',
  answeredNo: 'لم تأخذ خلوتك بعد — لا يزال الوقت أمامك 💙',
  answerSheetTitle: 'سجل خلوتك اليوم',
  answerSheetSubtitle: 'اختار الإجابة وسجّل الجزء اللي قريته.',
  answerBook: 'السفر',
  selectBookFirst: 'اختار السفر الأول',
  oldTestament: 'العهد القديم',
  newTestament: 'العهد الجديد',
  answerChapter: 'الإصحاحات',
  answerRangeHint: 'اختار أي إصحاحات حابب تقراها، ومش لازم يكونوا ورا بعض.',
  readingSelectionRequiredTitle: 'اختيار القراءة مطلوب',
  readingSelectionRequiredMessage: 'لازم تختار سفر وإصحاح واحد على الأقل قبل الحفظ.',
  permissionNoticeTitle: 'فعّل التذكير اليومي',
  permissionNoticeBody:
    'لو الإشعارات مقفولة، مش هيوصلك تذكير بوقتك مع ربنا في المعاد المناسب.',
  permissionEnable: 'تفعيل الإشعارات',
  permissionOpenSettings: 'فتح الإعدادات',
  saveAnswer: 'حفظ الإجابة',
  savedOfflineMessage:
    'تم حفظ التغيير على الجهاز، وسيتم إرساله تلقائياً عند عودة الإنترنت.',
  quickActions: {
    devotionGuide: 'شرح الخلوة',
    settings: 'اعدادات الخلوة',
    calendar: 'متابعة وقتك مع الله',
    badges: 'الأوسمة والجوائز',
    bibleMemorization: 'حفظ الكتاب المقدس',
  },
} as const;
