export const homeStrings = {
  dailyQuestion: 'هل أخذت خلوتك اليوم؟',
  yesMessage:
    'رائع! 🎉 ثابر على هذا الوقت الثمين مع الله يومياً\n"أَقِيمُوا فِيَّ وَأَنَا فِيكُمْ" يوحنا ١٥:٤',
  noMessage:
    'لا بأس 💙 لا يزال الوقت أمامك اليوم\nحتى ١٠ دقائق هادئة مع الله تغيّر يومك بالكامل',
  logoutTitle: 'تسجيل الخروج',
  logoutMessage: 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
  cancel: 'إلغاء',
  logout: 'خروج',
  correctStreakTitle: 'أحسنت! استمر مع الله 🙏',
  startNowTitle: 'لا بأس، الله ينتظرك 💙',
  startNowAction: 'ابدأ خلوتي الآن',
  later: 'لاحقاً',
  answerPrompt: 'قضيت وقتاً مع الله اليوم؟',
  yes: 'نعم ✓',
  no: 'لا ✗',
  featurePrayerNotesTitle: 'طلبات الصلاة',
  featurePrayerNotesSubtitle: 'شارك صلواتك وطلباتك',
  featureReflectionTitle: 'اليوميات',
  featureReflectionSubtitle: 'سجل خواطرك اليومية',
  headerGreeting: 'مرحباً يا بطل 👋',
  headerSubGreeting: 'جاهز لوقتك مع الله النهاردة؟',
  dailyCardLabel: 'سؤال اليوم المتغير',
  answerNow: 'جاوب الآن',
  editAnswer: 'تعديل الإجابة',
  answeredYes: 'أجبت بنعم اليوم 🎉 بارك الله خلوتك!',
  answeredNo: 'لم تأخذ خلوتك بعد — لا يزال الوقت أمامك 💙',
  answerSheetTitle: 'سجل خلوتك اليوم',
  answerSheetSubtitle: 'اختار الإجابة وسجّل الجزء اللي قريته.',
  answerBook: 'السفر',
  answerChapter: 'الإصحاح',
  answerVerses: 'عدد الإصحاحات',
  saveAnswer: 'حفظ الإجابة',
  quickActions: {
    devotionGuide: 'شرح الخلوة',
    settings: 'اعدادات الخلوة',
    badges: 'الأوسمة والجوائز',
    bibleMemorization: 'حفظ الكتاب المقدس',
  },
} as const;
