export const profileStrings = {
  defaultUser: 'مستخدم',
  validation: {
    fullNameRequired: 'يرجى إدخال الاسم',
    phoneInvalid: 'يرجى إدخال رقم هاتف صحيح',
  },
  saveSuccessTitle: 'تم الحفظ',
  saveSuccessMessage: 'تم تحديث بياناتك بنجاح.',
  saveOfflineMessage:
    'تم حفظ بياناتك على الجهاز، وسيتم مزامنتها تلقائياً عند عودة الإنترنت.',
  saveErrorTitle: 'خطأ',
  saveErrorMessage: 'حدث خطأ أثناء حفظ البيانات.',
  logoutTitle: 'تسجيل الخروج',
  logoutMessage: 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
  cancel: 'إلغاء',
  logout: 'خروج',
  noSessionTitle: 'لا توجد جلسة نشطة',
  noSessionMessage: 'سجّل الدخول أولاً للوصول إلى الملف الشخصي.',
  title: 'الملف الشخصي',
  accountSavedBadge: 'بياناتك محفوظة على الحساب',
  basicInfoTitle: 'البيانات الأساسية',
  basicInfoSubtitle: 'يمكنك تعديل الاسم والهاتف والبيانات الشخصية من هنا.',
  name: 'الاسم',
  namePlaceholder: 'أدخل اسمك',
  email: 'البريد الإلكتروني',
  emailPlaceholder: 'البريد الإلكتروني',
  phone: 'رقم الهاتف',
  phonePlaceholder: 'أدخل رقم هاتفك',
  fixed: 'ثابت',
  churchTitle: 'الكنيسة والانتماء',
  churchSubtitle: 'أضف معلوماتك الكنسية لتبقى بياناتك مكتملة.',
  church: 'الكنيسة',
  churchPlaceholder: 'اسم الكنيسة',
  sect: 'الطائفة',
  sectPlaceholder: 'اسم الطائفة',
  optional: 'اختياري',
  personalTitle: 'بيانات شخصية وروحية',
  personalSubtitle: 'اضبط تاريخ الميلاد والجنس من هنا.',
  birthDate: 'تاريخ الميلاد',
  birthDatePlaceholder: 'اختر تاريخ الميلاد',
  gender: 'الجنس',
  male: 'ذكر',
  female: 'أنثى',
  save: 'حفظ التغييرات',
  noChanges: 'لا توجد تغييرات',
  saving: 'جارٍ الحفظ...',
  datePickerTitle: 'تاريخ الميلاد',
  confirm: 'تأكيد',
} as const;
