export const spiritualReflectionStrings = {
  title: 'التأمل الروحي',
  headerEyebrow: 'مساحة هادية',
  heroBadge: 'يومياتك مع ربنا',
  heroTitle: 'اكتب اللي لمسه ربنا في قلبك',
  heroText:
    'سجّل لمسات ربنا، آية أثرت فيك، أو فكرة صغيرة عايز ترجع لها بعدين.',
  totalReflections: 'إجمالي التأملات',
  latestReflection: 'آخر تأمل',
  noReflectionsYet: 'لسه ماكتبتش تأملات',
  searchPlaceholder: 'ابحث في التأملات...',
  errors: {
    genericTitle: 'خطأ',
  },
  deleteTitle: 'حذف التأمل',
  deleteMessage: 'هل تريد حذف هذا التأمل؟',
  cancel: 'إلغاء',
  delete: 'حذف',
  emptyTitle: 'لا يوجد تأملات بعد',
  emptyMessage: 'اضغط + لإنشاء تامل.',
  detailTitle: 'تفاصيل التأمل',
  close: 'إغلاق',
  edit: 'تعديل',
  editor: {
    editTitle: 'تعديل التأمل',
    newTitle: 'تأمل جديد',
    hint: 'ماذا كلّمك الله اليوم؟',
    placeholder: 'اكتب هنا...',
    saveEdit: 'حفظ التعديل',
    addReflection: 'إضافة التأمل',
    add: 'إضافة',
  },
  voice: {
    add: 'تسجيل صوتي',
    recording: 'جاري التسجيل',
    play: 'تشغيل التسجيل',
    stop: 'إيقاف',
    delete: 'حذف',
    permissionDenied: 'يحتاج التطبيق إذن الميكروفون لتسجيل الصوت.',
    error: 'تعذر التعامل مع التسجيل الصوتي.',
    fallbackTitle: 'تسجيل صوتي',
  },
} as const;
