import { StyleSheet } from 'react-native';
import { GOLD, NAVY } from './utils';
import {
  heroBadgeBase,
  heroBadgeTextBase,
  heroCardBase,
  heroGlowBase,
  heroIconWrapBase,
  heroTextBase,
  heroTitleBase,
  heroTopRowBase,
  heroEyebrowBase,
} from '../shared/heroStyles';

export const memorizationStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F2F4F8' },
  flex: { flex: 1 },
  header: {
    backgroundColor: NAVY,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 16,
  },
  backBtn: { padding: 4 },
  headerSpacer: { width: 40 },
  headerTitle: { color: '#FFF', fontSize: 18, fontWeight: 'bold' },
  content: { padding: 20, paddingBottom: 48 },
  tabPanelContent: {
    paddingTop: 14,
  },
  segmentedWrap: {
    flexDirection: 'row',
    gap: 6,
    marginHorizontal: 20,
    marginTop: 14,
    padding: 4,
    backgroundColor: '#E7EAF0',
    borderRadius: 14,
  },
  segmentedOption: {
    flex: 1,
    minHeight: 42,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  segmentedOptionActive: {
    backgroundColor: '#FFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 1,
  },
  segmentedOptionText: {
    color: '#666D77',
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'center',
  },
  segmentedOptionTextActive: {
    color: NAVY,
  },
  heroCard: {
    ...heroCardBase,
    marginBottom: 14,
  },
  heroGlow: {
    ...heroGlowBase,
  },
  heroTopRow: {
    ...heroTopRowBase,
    marginBottom: 12,
  },
  heroIconWrap: {
    ...heroIconWrapBase,
  },
  heroBadge: {
    ...heroBadgeBase,
  },
  heroBadgeText: {
    ...heroBadgeTextBase,
  },
  heroEyebrow: {
    ...heroEyebrowBase,
  },
  heroTitle: {
    ...heroTitleBase,
  },
  heroText: {
    ...heroTextBase,
  },
  selectionSummary: {
    backgroundColor: '#FFF',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.06)',
  },
  summaryItem: {
    flex: 1,
  },
  summaryLabel: {
    color: '#7C8087',
    fontSize: 12,
    marginBottom: 4,
  },
  summaryValue: {
    color: NAVY,
    fontSize: 15,
    fontWeight: '700',
  },
  summaryDivider: {
    width: 1,
    alignSelf: 'stretch',
    backgroundColor: 'rgba(10,17,36,0.08)',
    marginHorizontal: 12,
  },
  sectionCard: {
    backgroundColor: '#FFF',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.06)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 1,
  },
  sectionHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    gap: 10,
  },
  sectionIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: 'rgba(10,17,36,0.05)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectionHeadingText: {
    flex: 1,
  },
  infoCard: {
    backgroundColor: '#F7F1DF',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: 'rgba(201,168,76,0.22)',
    marginBottom: 14,
  },
  sectionLabel: {
    fontSize: 14,
    color: '#8A8F98',
    textAlign: 'left',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  sectionCaption: {
    color: '#666D77',
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 2,
  },
  subSectionLabel: {
    fontSize: 15,
    color: NAVY,
    textAlign: 'left',
    fontWeight: '700',
    marginTop: 4,
    marginBottom: 8,
  },
  helperText: {
    color: '#777',
    fontSize: 12,
    textAlign: 'left',
    marginTop: 8,
    marginBottom: 12,
    lineHeight: 20,
  },
  fieldBlock: {
    marginBottom: 8,
  },
  modeRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  modeChip: {
    flex: 1,
    backgroundColor: '#E8E8E8',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  modeChipCompact: {
    paddingVertical: 10,
  },
  modeChipActive: {
    backgroundColor: NAVY,
    borderColor: NAVY,
  },
  modeChipText: {
    color: '#555',
    fontSize: 14,
    fontWeight: '600',
  },
  modeChipTextCompact: {
    fontSize: 13,
  },
  modeChipTextActive: {
    color: '#FFF',
  },
  levelRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  levelChip: {
    flex: 1,
    backgroundColor: '#E8E8E8',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  levelChipActive: {
    backgroundColor: NAVY,
    borderColor: NAVY,
  },
  levelChipText: {
    color: '#555',
    fontSize: 14,
    fontWeight: '600',
  },
  levelChipTextActive: {
    color: '#FFF',
  },
  primaryBtn: {
    backgroundColor: NAVY,
    borderRadius: 14,
    paddingVertical: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginTop: 24,
    shadowColor: NAVY,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 3,
  },
  primaryBtnText: { color: '#FFF', fontSize: 16, fontWeight: 'bold' },
  ghostBtn: {
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 12,
  },
  ghostBtnText: { color: '#888', fontSize: 15 },
  refText: {
    color: GOLD,
    fontWeight: 'bold',
    textAlign: 'left',
    marginBottom: 6,
    fontSize: 14,
  },
  instructionText: {
    color: '#666',
    textAlign: 'left',
    fontSize: 14,
    lineHeight: 22,
  },
  verseBox: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 18,
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.06)',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 4,
  },
  verseBoxHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(10,17,36,0.06)',
  },
  verseBoxTitle: {
    color: NAVY,
    fontSize: 14,
    fontWeight: '700',
  },
  statusPillsRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.06)',
  },
  statusPillText: {
    color: NAVY,
    fontSize: 13,
    fontWeight: '700',
  },
  wordsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    gap: 6,
    alignItems: 'center',
  },
  wordText: {
    fontSize: 18,
    color: '#222',
    textAlign: 'left',
  },
  blankInput: {
    height: 42,
    minWidth: 72,
    borderWidth: 1.5,
    borderColor: 'rgba(10,17,36,0.18)',
    borderBottomWidth: 2,
    borderBottomColor: NAVY,
    borderRadius: 10,
    fontSize: 16,
    fontWeight: '700',
    color: NAVY,
    paddingHorizontal: 10,
    paddingVertical: 0,
    backgroundColor: '#FAFBFD',
  },
  fullVerseInput: {
    minHeight: 150,
    borderWidth: 1.5,
    borderColor: 'rgba(10,17,36,0.12)',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 14,
    backgroundColor: '#FAFBFD',
    color: NAVY,
    fontSize: 16,
    lineHeight: 26,
    textAlign: 'left',
  },
  scoreBox: { alignItems: 'center', marginBottom: 24 },
  resultHeroCard: {
    ...heroCardBase,
    alignItems: 'stretch',
    marginBottom: 16,
  },
  resultHeroGlow: {
    ...heroGlowBase,
  },
  resultHeroTopRow: {
    ...heroTopRowBase,
    marginBottom: 14,
  },
  resultHeroBadge: {
    ...heroBadgeBase,
  },
  resultHeroBadgeText: {
    ...heroBadgeTextBase,
  },
  resultHeroIconWrap: {
    ...heroIconWrapBase,
  },
  scoreText: {
    fontSize: 42,
    fontWeight: '900',
    color: '#FFF',
    marginBottom: 8,
    textAlign: 'left',
  },
  scoreLabel: {
    ...heroEyebrowBase,
    marginBottom: 4,
  },
  resultHeroMessage: {
    ...heroTextBase,
    marginBottom: 16,
  },
  resultToneBadge: {
    alignSelf: 'flex-start',
    marginBottom: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  resultToneBadgeText: {
    color: '#FFF4D6',
    fontSize: 13,
    fontWeight: '800',
  },
  resultStatsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  resultActionsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 12,
  },
  resultSecondaryBtn: {
    flex: 1,
    minHeight: 52,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.12)',
    backgroundColor: '#FFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingHorizontal: 10,
  },
  resultSecondaryBtnText: {
    color: NAVY,
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
  },
  resultHomeBtn: {
    flex: 1,
    minHeight: 52,
    borderRadius: 14,
    backgroundColor: GOLD,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingHorizontal: 10,
    shadowColor: GOLD,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.16,
    shadowRadius: 10,
    elevation: 2,
  },
  resultHomeBtnText: {
    color: '#FFF',
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
  },
  resultStatCard: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    paddingVertical: 14,
    paddingHorizontal: 12,
    alignItems: 'center',
  },
  resultStatNumber: {
    color: '#FFF',
    fontSize: 24,
    fontWeight: '800',
    marginBottom: 4,
  },
  resultStatLabel: {
    color: 'rgba(255,255,255,0.68)',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  resultMetaLabel: {
    color: '#7C8087',
    fontSize: 12,
    marginBottom: 4,
  },
  resultSlot: {
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  resultCorrect: { backgroundColor: 'rgba(52,199,89,0.18)' },
  resultWrong: { backgroundColor: 'rgba(255,59,48,0.12)' },
  resultSlotText: {
    fontSize: 15,
    textAlign: 'left',
  },
  resultSlotCorrectText: { color: '#1A7A1A', fontWeight: 'bold' },
  resultSlotWrongText: { color: '#CC0000' },

  // Stats Dashboard
  statsCard: {
    backgroundColor: '#FFF',
    borderRadius: 24,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.06)',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
  },
  statsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  statsTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: NAVY,
  },
  historyTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: NAVY,
    marginBottom: 12,
    marginTop: 8,
  },
  historyRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  historyInfo: {
    flex: 1,
  },
  historyScore: {
    alignItems: 'flex-end',
  },
  historyDeleteBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: 'rgba(210,74,67,0.09)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  statItem: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: '#F8F9FB',
    borderRadius: 16,
    padding: 12,
  },
  statValue: {
    fontSize: 18,
    fontWeight: '800',
    color: GOLD,
    marginBottom: 2,
  },
  statLabel: {
    fontSize: 12,
    color: '#8A8F98',
  },
  progressBox: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(10,17,36,0.06)',
  },
  progressBarContainer: {
    height: 8,
    backgroundColor: '#EDF0F5',
    borderRadius: 4,
    marginVertical: 10,
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    backgroundColor: GOLD,
    borderRadius: 4,
  },
  progressText: {
    fontSize: 13,
    color: '#666D77',
    fontWeight: '600',
  },
  insightGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 16,
  },
  insightItem: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: '#F8F9FB',
    borderRadius: 14,
    padding: 12,
  },
  insightValue: {
    color: NAVY,
    fontSize: 17,
    fontWeight: '900',
    marginTop: 8,
  },
  insightLabel: {
    color: '#7C8087',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 2,
  },
  statsSubTitle: {
    color: NAVY,
    fontSize: 14,
    fontWeight: '900',
    marginTop: 16,
    marginBottom: 10,
    textAlign: 'left',
  },
  difficultyBox: {
    marginTop: 4,
  },
  difficultyRow: {
    minHeight: 42,
    borderRadius: 12,
    backgroundColor: '#F8F9FB',
    paddingHorizontal: 12,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  difficultyLabel: {
    flex: 1,
    color: NAVY,
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'left',
  },
  difficultyValue: {
    color: GOLD,
    fontSize: 13,
    fontWeight: '900',
  },
  goalBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(201,168,76,0.1)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  goalBtnText: {
    fontSize: 12,
    color: GOLD,
    fontWeight: '700',
  },

  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    padding: 24,
  },
  modalContent: {
    backgroundColor: '#FFF',
    borderRadius: 24,
    padding: 24,
    alignItems: 'center',
  },
  goalModalContent: {
    width: '100%',
    maxHeight: '88%',
    alignItems: 'stretch',
    padding: 18,
  },
  goalModalScroll: {
    paddingBottom: 4,
  },
  goalModalHeader: {
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: NAVY,
    marginTop: 12,
    marginBottom: 8,
  },
  modalCaption: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    marginBottom: 24,
  },
  goalPeriodRow: {
    flexDirection: 'row',
    gap: 8,
    backgroundColor: '#EFF3F8',
    borderRadius: 14,
    padding: 5,
    marginBottom: 18,
  },
  goalPeriodOption: {
    flex: 1,
    minHeight: 40,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  goalPeriodOptionActive: {
    backgroundColor: NAVY,
  },
  goalPeriodText: {
    color: NAVY,
    fontSize: 13,
    fontWeight: '900',
  },
  goalPeriodTextActive: {
    color: '#FFF',
  },
  goalInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
    gap: 18,
    marginBottom: 32,
  },
  goalValueBlock: {
    width: 96,
    alignItems: 'center',
    justifyContent: 'center',
  },
  goalValue: {
    fontSize: 48,
    fontWeight: '900',
    color: GOLD,
    width: '100%',
    textAlign: 'center',
  },
  goalUnitText: {
    color: '#8A8F98',
    fontSize: 12,
    fontWeight: '800',
    marginTop: -4,
  },
  goalAdjustBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#F2F4F8',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalSaveBtn: {
    backgroundColor: NAVY,
    width: '100%',
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
  },
  modalSaveBtnText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '700',
  },
});
