import { StyleSheet } from 'react-native';
import { GOLD, NAVY } from './utils';
import {
  heroBadgeBase,
  heroBadgeTextBase,
  heroCardBase,
  heroGlowBase,
  heroIconWrapBase,
  heroTextBase,
  heroTitleBase,
  heroTopRowBase,
  heroEyebrowBase,
} from '../shared/heroStyles';

export const memorizationStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F2F4F8' },
  flex: { flex: 1 },
  header: {
    backgroundColor: NAVY,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 16,
  },
  backBtn: { padding: 4 },
  headerSpacer: { width: 40 },
  headerTitle: { color: '#FFF', fontSize: 18, fontWeight: 'bold' },
  content: { padding: 20, paddingBottom: 48 },
  heroCard: {
    ...heroCardBase,
    marginBottom: 14,
  },
  heroGlow: {
    ...heroGlowBase,
  },
  heroTopRow: {
    ...heroTopRowBase,
    marginBottom: 12,
  },
  heroIconWrap: {
    ...heroIconWrapBase,
  },
  heroBadge: {
    ...heroBadgeBase,
  },
  heroBadgeText: {
    ...heroBadgeTextBase,
  },
  heroEyebrow: {
    ...heroEyebrowBase,
  },
  heroTitle: {
    ...heroTitleBase,
  },
  heroText: {
    ...heroTextBase,
  },
  selectionSummary: {
    backgroundColor: '#FFF',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.06)',
  },
  summaryItem: {
    flex: 1,
  },
  summaryLabel: {
    color: '#7C8087',
    fontSize: 12,
    marginBottom: 4,
  },
  summaryValue: {
    color: NAVY,
    fontSize: 15,
    fontWeight: '700',
  },
  summaryDivider: {
    width: 1,
    alignSelf: 'stretch',
    backgroundColor: 'rgba(10,17,36,0.08)',
    marginHorizontal: 12,
  },
  sectionCard: {
    backgroundColor: '#FFF',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.06)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 1,
  },
  sectionHeadingText: {
    flex: 1,
  },
  infoCard: {
    backgroundColor: '#F7F1DF',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: 'rgba(201,168,76,0.22)',
    marginBottom: 14,
  },
  sectionLabel: {
    fontSize: 14,
    color: '#8A8F98',
    textAlign: 'left',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  sectionCaption: {
    color: '#666D77',
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 2,
  },
  subSectionLabel: {
    fontSize: 15,
    color: NAVY,
    textAlign: 'left',
    fontWeight: '700',
    marginTop: 4,
    marginBottom: 8,
  },
  helperText: {
    color: '#777',
    fontSize: 12,
    textAlign: 'left',
    marginTop: 8,
    marginBottom: 12,
    lineHeight: 20,
  },
  fieldBlock: {
    marginBottom: 8,
  },
  modeRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  modeChip: {
    flex: 1,
    backgroundColor: '#E8E8E8',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  modeChipCompact: {
    paddingVertical: 10,
  },
  modeChipActive: {
    backgroundColor: NAVY,
    borderColor: NAVY,
  },
  modeChipText: {
    color: '#555',
    fontSize: 14,
    fontWeight: '600',
  },
  modeChipTextCompact: {
    fontSize: 13,
  },
  modeChipTextActive: {
    color: '#FFF',
  },
  levelRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  levelChip: {
    flex: 1,
    backgroundColor: '#E8E8E8',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  levelChipActive: {
    backgroundColor: NAVY,
    borderColor: NAVY,
  },
  levelChipText: {
    color: '#555',
    fontSize: 14,
    fontWeight: '600',
  },
  levelChipTextActive: {
    color: '#FFF',
  },
  primaryBtn: {
    backgroundColor: NAVY,
    borderRadius: 14,
    paddingVertical: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginTop: 24,
    shadowColor: NAVY,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 3,
  },
  primaryBtnText: { color: '#FFF', fontSize: 16, fontWeight: 'bold' },
  ghostBtn: {
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 12,
  },
  ghostBtnText: { color: '#888', fontSize: 15 },
  refText: {
    color: GOLD,
    fontWeight: 'bold',
    textAlign: 'left',
    marginBottom: 6,
    fontSize: 14,
  },
  instructionText: {
    color: '#666',
    textAlign: 'left',
    fontSize: 14,
    lineHeight: 22,
  },
  verseBox: {
    
    backgroundColor: '#FFF',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 18,
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.06)',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 4,
  },
  verseBoxHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(10,17,36,0.06)',
  },
  verseBoxTitle: {
    color: NAVY,
    fontSize: 14,
    fontWeight: '700',
  },
  statusPillsRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.06)',
  },
  statusPillText: {
    color: NAVY,
    fontSize: 13,
    fontWeight: '700',
  },
  wordsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    gap: 6,
    alignItems: 'center',
  },
  wordText: {
    fontSize: 18,
    color: '#222',
    textAlign: 'left',
  },
  blankInput: {
    height: 42,
    minWidth: 72,
    borderWidth: 1.5,
    borderColor: 'rgba(10,17,36,0.18)',
    borderBottomWidth: 2,
    borderBottomColor: NAVY,
    borderRadius: 10,
    fontSize: 16,
    fontWeight: '700',
    color: NAVY,
    paddingHorizontal: 10,
    paddingVertical: 0,
    backgroundColor: '#FAFBFD',
  },
  fullVerseInput: {
    minHeight: 150,
    borderWidth: 1.5,
    borderColor: 'rgba(10,17,36,0.12)',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 14,
    backgroundColor: '#FAFBFD',
    color: NAVY,
    fontSize: 16,
    lineHeight: 26,
    textAlign: 'left',
  },
  scoreBox: { alignItems: 'center', marginBottom: 24 },
  resultHeroCard: {
    ...heroCardBase,
    alignItems: 'stretch',
    marginBottom: 16,
  },
  resultHeroGlow: {
    ...heroGlowBase,
  },
  resultHeroTopRow: {
    ...heroTopRowBase,
    marginBottom: 14,
  },
  resultHeroBadge: {
    ...heroBadgeBase,
  },
  resultHeroBadgeText: {
    ...heroBadgeTextBase,
  },
  resultHeroIconWrap: {
    ...heroIconWrapBase,
  },
  scoreText: {
    fontSize: 42,
    fontWeight: '900',
    color: '#FFF',
    marginBottom: 8,
    textAlign: 'left',
  },
  scoreLabel: {
    ...heroEyebrowBase,
    marginBottom: 4,
  },
  resultHeroMessage: {
    ...heroTextBase,
    marginBottom: 16,
  },
  resultToneBadge: {
    alignSelf: 'flex-start',
    marginBottom: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  resultToneBadgeText: {
    color: '#FFF4D6',
    fontSize: 13,
    fontWeight: '800',
  },
  resultStatsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  resultStatCard: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    paddingVertical: 14,
    paddingHorizontal: 12,
    alignItems: 'center',
  },
  resultStatNumber: {
    color: '#FFF',
    fontSize: 24,
    fontWeight: '800',
    marginBottom: 4,
  },
  resultStatLabel: {
    color: 'rgba(255,255,255,0.68)',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  resultMetaLabel: {
    color: '#7C8087',
    fontSize: 12,
    marginBottom: 4,
  },
  resultSlot: {
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  resultCorrect: { backgroundColor: 'rgba(52,199,89,0.18)' },
  resultWrong: { backgroundColor: 'rgba(255,59,48,0.12)' },
  resultSlotText: {
    fontSize: 15,
    textAlign: 'left',
  },
  resultSlotCorrectText: { color: '#1A7A1A', fontWeight: 'bold' },
  resultSlotWrongText: { color: '#CC0000' },
});
