import { StyleSheet } from 'react-native';
import { BG, GOLD, NAVY, palette } from '../shared/designTokens';
import {
  heroBadgeBase,
  heroBadgeTextBase,
  heroCardBase,
  heroGlowBase,
  heroIconWrapBase,
  heroTextBase,
  heroTitleBase,
  heroTopRowBase,
} from '../shared/heroStyles';

export { GOLD, NAVY };

export const SKY = BG;
export const SLATE = palette.mutedText;
export const INK = palette.text;

export const dailyNotificationStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: BG },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  topInset: { backgroundColor: NAVY },
  header: {
    backgroundColor: NAVY,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 16,
  },
  backBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerSpacer: { width: 40 },
  headerTitle: { color: '#FFF', fontSize: 19, fontWeight: '800' },
  content: { padding: 18, paddingBottom: 40 },
  heroCard: {
    ...heroCardBase,
    padding: 22,
  },
  heroGlow: {
    ...heroGlowBase,
  },
  heroTopRow: {
    ...heroTopRowBase,
    marginBottom: 18,
  },
  heroBadge: {
    ...heroBadgeBase,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  heroBadgeText: {
    ...heroBadgeTextBase,
  },
  heroIconWrap: {
    ...heroIconWrapBase,
  },
  heroTitle: {
    ...heroTitleBase,
    fontSize: 25,
    lineHeight: 34,
    marginBottom: 10,
  },
  heroSubtitle: {
    ...heroTextBase,
    lineHeight: 23,
    marginBottom: 18,
  },
  timePanel: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    marginBottom: 16,
  },
  timePanelIcon: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: '#78A1BD',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 14,
  },
  timePanelBody: {
    flex: 1,
  },
  timeLabel: {
    color: 'rgba(255,255,255,0.64)',
    fontSize: 13,
    marginBottom: 4,
    textAlign: 'left',
  },
  timeText: {
    color: '#FFF',
    fontSize: 30,
    fontWeight: '800',
    textAlign: 'left',
    letterSpacing: 0.2,
  },
  pickerCard: {
    backgroundColor: '#FFF',
    borderRadius: 24,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#0B1A33',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 18,
    elevation: 3,
  },
  inlineTimeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFD',
    borderRadius: 18,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E3E8F1',
    marginBottom: 8,
  },
  inlineTimeIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: '#78A1BD',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 12,
  },
  inlineTimeBody: {
    flex: 1,
    paddingHorizontal: 12,
  },
  inlineTimeLabel: {
    color: '#667085',
    fontSize: 12,
    marginBottom: 0,
    marginTop: 4,
    textAlign: 'left',
  },
  inlineTimeValue: {
    color: NAVY,
    fontSize: 17,
    fontWeight: '800',
    textAlign: 'left',
  },
  iosPicker: { alignSelf: 'center' },
  saveBtn: {
    backgroundColor: '#78A1BD',
    borderRadius: 18,
    paddingVertical: 18,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginBottom: 28,
    elevation: 5,
    shadowColor: '#78A1BD',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.28,
    shadowRadius: 18,
  },
  saveBtnDisabled: { opacity: 0.6 },
  saveBtnText: { color: '#FFF', fontSize: 16, fontWeight: '800' },
  sectionHeader: {
    textAlign: 'left',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: NAVY,
    textAlign: 'left',
    marginBottom: 4,
  },
  sectionSubtitle: {
    color: SLATE,
    fontSize: 13,
    textAlign: 'left',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(10,17,36,0.35)',
  },
  pickerSheet: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 26,
  },
  pickerHandle: {
    width: 42,
    height: 5,
    borderRadius: 999,
    backgroundColor: '#D4DAE4',
    alignSelf: 'center',
    marginBottom: 14,
  },
  pickerHeader: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  pickerTitleWrap: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  pickerTitle: {
    color: NAVY,
    fontSize: 16,
    fontWeight: '800',
    textAlign: 'center',
  },
  pickerSubtitle: {
    color: SLATE,
    fontSize: 12,
    marginTop: 4,
    textAlign: 'center',
  },
  pickerActionSecondary: {
    color: '#667085',
    fontSize: 15,
    fontWeight: '700',
  },
  pickerActionPrimary: {
    color: NAVY,
    fontSize: 15,
    fontWeight: '800',
  },
  fieldLabel: {
    color: INK,
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 8,
    marginTop: 8,
    textAlign: 'left',
  },
  rangeHint: {
    color: '#667085',
    fontSize: 12,
    lineHeight: 18,
    marginTop: -2,
    marginBottom: 8,
    textAlign: 'left',
  },
  multiReadingHint: {
    color: '#667085',
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 12,
    textAlign: 'left',
  },
  openSuggestionsCard: {
    backgroundColor: '#F8FAFD',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E3E8F1',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
    gap: 10,
  },
  openSuggestionsIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#78A1BD',
    alignItems: 'center',
    justifyContent: 'center',
  },
  openSuggestionsBody: {
    flex: 1,
  },
  openSuggestionsTitle: {
    color: NAVY,
    fontSize: 15,
    fontWeight: '900',
    marginBottom: 3,
    textAlign: 'left',
  },
  openSuggestionsText: {
    color: '#667085',
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'left',
  },
  suggestionsScreenContent: {
    padding: 18,
    paddingBottom: 40,
  },
  suggestionsScreenIntro: {
    marginBottom: 14,
  },
  suggestionsScreenHeading: {
    color: NAVY,
    fontSize: 22,
    fontWeight: '900',
    marginBottom: 6,
    textAlign: 'left',
  },
  suggestionsScreenBody: {
    color: SLATE,
    fontSize: 13,
    lineHeight: 22,
    textAlign: 'left',
  },
  planSuggestionScreenCard: {
    backgroundColor: '#FFF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.06)',
    padding: 14,
    marginBottom: 12,
    shadowColor: '#0B1A33',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 2,
  },
  planSuggestionTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  planSuggestionIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#78A1BD',
    alignItems: 'center',
    justifyContent: 'center',
  },
  planSuggestionBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#E9EDF4',
  },
  planSuggestionBadgeText: {
    color: '#667085',
    fontSize: 11,
    fontWeight: '900',
    textAlign: 'center',
  },
  planSuggestionScreenTitle: {
    color: NAVY,
    fontSize: 17,
    fontWeight: '900',
    marginBottom: 4,
    textAlign: 'left',
  },
  planSuggestionScreenText: {
    color: '#5C6676',
    fontSize: 13,
    lineHeight: 21,
    marginBottom: 12,
    textAlign: 'left',
  },
  planSuggestionMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'flex-start',
    backgroundColor: '#F2F5F9',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginBottom: 12,
  },
  planSuggestionMetaText: {
    color: NAVY,
    fontSize: 12,
    fontWeight: '800',
  },
  planDaysPreview: {
    backgroundColor: '#F8FAFD',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E3E8F1',
    padding: 10,
    gap: 8,
    marginBottom: 12,
  },
  planDayRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  planDayLabel: {
    minWidth: 58,
    color: GOLD,
    fontSize: 12,
    fontWeight: '900',
    textAlign: 'left',
  },
  planDayReading: {
    flex: 1,
    color: NAVY,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 18,
    textAlign: 'left',
  },
  planDaysMoreText: {
    color: '#667085',
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'left',
    marginTop: 2,
  },
  planDaysToggle: {
    alignSelf: 'flex-start',
    paddingVertical: 4,
  },
  planSuggestionScreenAction: {
    minHeight: 42,
    borderRadius: 12,
    backgroundColor: '#78A1BD',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  planSuggestionScreenActionText: {
    color: '#FFF',
    fontSize: 13,
    fontWeight: '900',
  },
  readingEntriesBox: {
    gap: 8,
    marginTop: 10,
    marginBottom: 10,
  },
  readingEntryRow: {
    backgroundColor: '#F8FAFD',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E3E8F1',
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  readingEntryText: {
    flex: 1,
    color: NAVY,
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 18,
    textAlign: 'left',
  },
  readingEntryRemove: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(255,59,48,0.10)',
  },
  readingEntryRemoveText: {
    color: '#B42318',
    fontSize: 11,
    fontWeight: '900',
  },
  addReadingEntryBtn: {
    minHeight: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    backgroundColor: '#78A1BD',
  },
  addReadingEntryBtnDisabled: {
    opacity: 0.55,
  },
  addReadingEntryText: {
    color: '#FFF',
    fontSize: 13,
    fontWeight: '900',
  },
  tipCard: {
    backgroundColor: '#FFF',
    borderRadius: 22,
    padding: 16,
    flexDirection: 'row-reverse',
    alignItems: 'flex-start',
    marginBottom: 12,
    shadowColor: '#0B1A33',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.05,
    shadowRadius: 18,
    elevation: 2,
  },
  tipIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: '#F2F5F9',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  tipBody: {
    flex: 1,
  },
  tipIndex: {
    color: GOLD,
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 4,
    textAlign: 'left',
  },
  tipText: {
    flex: 1,
    fontSize: 14,
    color: INK,
    textAlign: 'left',
    lineHeight: 24,
  },
});
