import { StyleSheet } from 'react-native';

export const NAVY = '#0A1124';
export const GOLD = '#C9A84C';
export const IVORY = '#F7F2E8';
export const SKY = '#EEF3F8';
export const SLATE = '#5C6676';
export const INK = '#1F2A3A';

export const dailyNotificationStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: SKY },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  topInset: { backgroundColor: NAVY },
  header: {
    backgroundColor: NAVY,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 16,
  },
  backBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerSpacer: { width: 40 },
  headerTitle: { color: '#FFF', fontSize: 19, fontWeight: '800' },
  content: { padding: 18, paddingBottom: 40 },
  heroCard: {
    backgroundColor: NAVY,
    borderRadius: 30,
    padding: 22,
    marginBottom: 18,
    overflow: 'hidden',
    shadowColor: NAVY,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 24,
    elevation: 8,
  },
  heroGlow: {
    position: 'absolute',
    top: -30,
    left: -20,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(201,168,76,0.14)',
  },
  heroTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  heroBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: IVORY,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  heroBadgeText: {
    color: NAVY,
    fontSize: 12,
    fontWeight: '800',
  },
  heroIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroTitle: {
    color: '#FFF',
    fontSize: 26,
    fontWeight: '800',
    lineHeight: 34,
    textAlign: 'left',
    marginBottom: 10,
  },
  heroSubtitle: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 14,
    lineHeight: 23,
    textAlign: 'left',
    marginBottom: 18,
  },
  timePanel: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    marginBottom: 16,
  },
  timePanelIcon: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: GOLD,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 14,
  },
  timePanelBody: {
    flex: 1,
  },
  timeLabel: {
    color: 'rgba(255,255,255,0.64)',
    fontSize: 13,
    marginBottom: 4,
    textAlign: 'left',
  },
  timeText: {
    color: '#FFF',
    fontSize: 30,
    fontWeight: '800',
    textAlign: 'left',
    letterSpacing: 0.2,
  },
  pickerCard: {
    backgroundColor: '#FFF',
    borderRadius: 24,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#0B1A33',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 18,
    elevation: 3,
  },
  iosPicker: { alignSelf: 'center' },
  saveBtn: {
    backgroundColor: GOLD,
    borderRadius: 18,
    paddingVertical: 18,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginBottom: 28,
    elevation: 5,
    shadowColor: GOLD,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.28,
    shadowRadius: 18,
  },
  saveBtnDisabled: { opacity: 0.6 },
  saveBtnText: { color: '#FFF', fontSize: 16, fontWeight: '800' },
  sectionHeader: {
    textAlign: 'left',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: NAVY,
    textAlign: 'left',
    marginBottom: 4,
  },
  sectionSubtitle: {
    color: SLATE,
    fontSize: 13,
    textAlign: 'left',
  },
  fieldLabel: {
    color: INK,
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 8,
    marginTop: 8,
    textAlign: 'left',
  },
  choiceRow: {
    flexDirection: 'row',
    gap: 8,
    paddingBottom: 8,
    paddingRight: 2,
  },
  choiceChip: {
     borderWidth: 1,
    borderColor: '#D6DEEA',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: '#FFF',
  },
  choiceChipSelected: {
    borderColor: NAVY,
    backgroundColor: NAVY,
  },
  choiceChipText: {
    color: NAVY,
    fontSize: 13,
    fontWeight: '600',
  },
  choiceChipTextSelected: {
    color: '#FFF',
  },
  testamentTabs: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
    backgroundColor: '#EFF3F8',
    borderRadius: 18,
    padding: 6,
  },
  testamentTab: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  testamentTabActive: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.06)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 1,
  },
  testamentTabIcon: {
    marginBottom: 4,
  },
  testamentTabText: {
    color: '#667085',
    fontSize: 13,
    fontWeight: '700',
  },
  testamentTabTextActive: {
    color: NAVY,
  },
  bookPanel: {
    backgroundColor: '#F8FAFD',
    borderRadius: 18,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E3E8F1',
    marginBottom: 8,
  },
  bookPanelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  bookPanelTitle: {
    color: NAVY,
    fontSize: 13,
    fontWeight: '800',
  },
  bookPanelCount: {
    color: '#667085',
    fontSize: 12,
    fontWeight: '700',
  },
  bookListScroll: {
    maxHeight: 60,
  },
  bookListContent: {
    flexDirection: 'row',
    gap: 8,
    paddingRight: 2,
  },
  bookChoiceChip: {
    minHeight: 44,
    justifyContent: 'center',
    borderRadius: 14,
  },
  bookChoiceChipText: {
    textAlign: 'center',
  },
  tipCard: {
    backgroundColor: '#FFF',
    borderRadius: 22,
    padding: 16,
    flexDirection: 'row-reverse',
    alignItems: 'flex-start',
    marginBottom: 12,
    shadowColor: '#0B1A33',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.05,
    shadowRadius: 18,
    elevation: 2,
  },
  tipIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: '#F2F5F9',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  tipBody: {
    flex: 1,
  },
  tipIndex: {
    color: GOLD,
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 4,
    textAlign: 'left',
  },
  tipText: {
    flex: 1,
    fontSize: 14,
    color: INK,
    textAlign: 'left',
    lineHeight: 24,
  },
});
