import { StyleSheet } from 'react-native';
import { AppTheme } from '../../lib/nightMode';
import { palette, radius, spacing } from '../shared/designTokens';

export const createStyles = (colors: AppTheme['colors']) =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scroll: {
      flex: 1,
    },
    content: {
      padding: spacing.lg,
      paddingBottom: spacing.xxxl,
    },
    intro: {
      color: colors.mutedText,
      fontSize: 13,
      fontWeight: '600',
      lineHeight: 20,
      textAlign: 'center',
      marginBottom: spacing.lg,
    },
    mapCard: {
      backgroundColor: colors.card,
      borderRadius: radius.xl,
      padding: spacing.sm,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: spacing.lg,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.08,
      shadowRadius: 16,
      elevation: 4,
    },
    legendRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.lg,
      paddingTop: spacing.md,
    },
    legendItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    legendDotVisited: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: '#2D9C5A',
    },
    legendDotCurrent: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: '#E6B84A',
    },
    legendDotLocked: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: 'transparent',
      borderWidth: 1.5,
      borderColor: '#AEB9C8',
    },
    legendText: {
      color: colors.mutedText,
      fontSize: 11,
      fontWeight: '700',
    },
    locationCard: {
      backgroundColor: colors.card,
      borderRadius: radius.xl,
      padding: spacing.lg,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: spacing.xl,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.08,
      shadowRadius: 16,
      elevation: 4,
    },
    locationTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: spacing.sm,
    },
    locationTitle: {
      color: colors.mutedText,
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 0.3,
    },
    currentStop: {
      color: colors.text,
      fontSize: 20,
      fontWeight: '900',
      textAlign: 'left',
    },
    daysWalked: {
      color: colors.mutedText,
      fontSize: 12,
      fontWeight: '700',
      marginTop: 2,
      marginBottom: spacing.md,
      textAlign: 'left',
    },
    progressTrack: {
      height: 8,
      borderRadius: radius.pill,
      backgroundColor: colors.cardMuted,
      overflow: 'hidden',
    },
    progressFill: {
      height: '100%',
      borderRadius: radius.pill,
      backgroundColor: palette.accent,
    },
    toNext: {
      color: colors.mutedText,
      fontSize: 12,
      fontWeight: '700',
      marginTop: spacing.sm,
      textAlign: 'left',
    },
    completeText: {
      color: palette.success,
      fontSize: 13,
      fontWeight: '800',
      lineHeight: 20,
      textAlign: 'left',
    },
    sectionTitle: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '900',
      marginBottom: spacing.md,
      textAlign: 'left',
    },
    stopList: {
      gap: spacing.sm,
      marginBottom: spacing.xl,
    },
    stopRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: spacing.md,
      backgroundColor: colors.card,
      borderRadius: radius.lg,
      padding: spacing.md,
      borderWidth: 1,
      borderColor: colors.border,
    },
    stopRowLocked: {
      opacity: 0.72,
    },
    stopIcon: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.cardMuted,
      marginTop: 2,
    },
    stopIconVisited: {
      backgroundColor: 'rgba(45,156,90,0.12)',
    },
    stopIconCurrent: {
      backgroundColor: 'rgba(230,184,74,0.16)',
    },
    stopBody: {
      flex: 1,
    },
    stopTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.sm,
    },
    stopName: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '800',
      flexShrink: 1,
      textAlign: 'left',
    },
    stopStatus: {
      color: colors.mutedText,
      fontSize: 10,
      fontWeight: '800',
      overflow: 'hidden',
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: radius.pill,
      backgroundColor: colors.cardMuted,
    },
    stopStatusVisited: {
      color: palette.success,
      backgroundColor: 'rgba(45,156,90,0.10)',
    },
    stopStatusCurrent: {
      color: '#B8860B',
      backgroundColor: 'rgba(230,184,74,0.16)',
    },
    stopVerseRef: {
      color: colors.accent,
      fontSize: 11,
      fontWeight: '800',
      marginTop: 2,
      marginBottom: 4,
      textAlign: 'left',
    },
    stopDescription: {
      color: colors.mutedText,
      fontSize: 12,
      lineHeight: 19,
      fontWeight: '500',
      textAlign: 'left',
    },
    footerVerse: {
      color: colors.mutedText,
      fontSize: 12,
      fontStyle: 'italic',
      lineHeight: 19,
      textAlign: 'center',
      paddingTop: spacing.lg,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
  });
