
auth.token=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

defaults.org=henarahaty
defaults.project=react-native

defaults.url=https://de.sentry.io/
