import { StyleSheet } from 'react-native';
import { BG, GOLD, NAVY } from './constants';

export const homeStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: BG },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: BG },
  topInset: { backgroundColor: NAVY },
  headerShell: {
    backgroundColor: NAVY,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 18,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  headerIdentity: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 12,
  },
  logoutBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarWrap: {
    width: 48,
    height: 48,
    marginRight: 12,
  },
  headerEyebrow: {
    color: '#E6D5A2',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'left',
    marginBottom: 2,
  },
  headerTitle: {
    color: '#FFF',
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '800',
    textAlign: 'left',
  },
  headerTextBlock: {
    flex: 1,
  },
  headerCaptionCard: {
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  headerCaption: {
    color: 'rgba(255,255,255,0.68)',
    fontSize: 12,
    lineHeight: 19,
    textAlign: 'left',
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: GOLD,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.16)',
  },
  avatarText: { color: NAVY, fontSize: 16, fontWeight: '800' },
  scrollContent: { padding: 16, paddingBottom: 36, gap: 14 },
  quickActionsSection: {
    marginBottom: 2,
  },
  homeSectionTitle: {
    color: NAVY,
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'left',
    marginBottom: 10,
  },
  buttonsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  quickBtn: {
    width: '31.2%',
    backgroundColor: '#FFF',
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 8,
    alignItems: 'center',
    minHeight: 104,
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.06)',
  },
  quickIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: '#F4F6FA',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  quickBtnText: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '800',
    color: NAVY,
    textAlign: 'center',
  },
  questionCard: {
    backgroundColor: NAVY,
    borderRadius: 22,
    padding: 18,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  questionDecor: {
    position: 'absolute',
    top: -42,
    right: -30,
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: 'rgba(201,168,76,0.13)',
  },
  questionTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  questionIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 13,
    backgroundColor: 'rgba(255,255,255,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  questionCardLabel: {
    fontSize: 12,
    color: '#E6D5A2',
    fontWeight: '800',
    textAlign: 'left',
  },
  questionText: {
    fontSize: 19,
    fontWeight: '900',
    color: '#FFF',
    textAlign: 'left',
    marginBottom: 16,
    lineHeight: 29,
  },
  answerBtn: {
    backgroundColor: GOLD,
    borderRadius: 14,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  answerBtnText: { color: '#FFF', fontSize: 15, fontWeight: '900' },
  answeredYesCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#2D9C5A',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 16,
    justifyContent: 'center',
  },
  answeredYesText: {
    color: '#FFF',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
    flex: 1,
  },
  answeredNoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#E67E22',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 16,
    justifyContent: 'center',
  },
  answeredNoText: {
    color: '#FFF',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
    flex: 1,
  },
  answeredBlock: {
    gap: 10,
  },
  editAnswerBtn: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.24)',
    borderRadius: 14,
    paddingVertical: 10,
    alignItems: 'center',
  },
  editAnswerBtnText: {
    color: '#FFF',
    fontSize: 13,
    fontWeight: '900',
  },
  sheetOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  sheetBackdrop: {
    flex: 1,
  },
  answerSheet: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 18,
    maxHeight: '80%',
  },
  answerSheetScrollContent: {
    paddingBottom: 4,
  },
  answerSheetTitle: {
    color: NAVY,
    fontSize: 19,
    fontWeight: '800',
    textAlign: 'left',
  },
  answerSheetSubtitle: {
    color: '#667085',
    fontSize: 13,
    marginTop: 6,
    marginBottom: 14,
    textAlign: 'left',
  },
  answerFieldTitle: {
    color: NAVY,
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 8,
    marginTop: 10,
    textAlign: 'left',
  },
  answerRangeHint: {
    color: '#667085',
    fontSize: 12,
    lineHeight: 18,
    marginTop: -2,
    marginBottom: 8,
    textAlign: 'left',
  },
  answerGroupLabel: {
    color: '#667085',
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 6,
  },
  answerTestamentTabs: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
    backgroundColor: '#EFF3F8',
    borderRadius: 18,
    padding: 6,
  },
  answerTestamentTab: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  answerTestamentTabActive: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.06)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 1,
  },
  answerTestamentTabText: {
    color: '#667085',
    fontSize: 13,
    fontWeight: '700',
  },
  answerTestamentTabTextActive: {
    color: NAVY,
  },
  answerBookPanel: {
    backgroundColor: '#F8FAFD',
    borderRadius: 18,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E3E8F1',
  },
  answerBookPanelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  answerBookPanelTitle: {
    color: NAVY,
    fontSize: 13,
    fontWeight: '800',
  },
  answerBookPanelCount: {
    color: '#667085',
    fontSize: 12,
    fontWeight: '700',
  },
  answerChoiceRow: {
    gap: 8,
    paddingBottom: 8,
  },
  answerChoiceChip: {
    borderWidth: 1,
    borderColor: '#CED8E5',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: '#F6F9FC',
  },
  answerBookChoiceChip: {
    minHeight: 44,
    justifyContent: 'center',
    borderRadius: 14,
  },
  answerChoiceChipSelected: {
    borderColor: NAVY,
    backgroundColor: NAVY,
  },
  answerChoiceText: {
    color: NAVY,
    fontSize: 13,
    fontWeight: '600',
  },
  answerBookChoiceText: {
    textAlign: 'center',
  },
  answerRangeSummaryCard: {
    backgroundColor: '#F8FAFD',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E3E8F1',
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginTop: 4,
  },
  answerRangeSummaryLabel: {
    color: '#667085',
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 4,
  },
  answerRangeSummaryValue: {
    color: NAVY,
    fontSize: 15,
    fontWeight: '800',
  },
  answerChoiceTextSelected: {
    color: '#FFF',
  },
  answerBinaryRow: {
    flexDirection: 'row',
    gap: 10,
  },
  answerBinaryBtn: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#CED8E5',
    alignItems: 'center',
    backgroundColor: '#F6F9FC',
  },
  answerBinaryBtnSelected: {
    backgroundColor: NAVY,
    borderColor: NAVY,
  },
  answerBinaryText: {
    color: NAVY,
    fontSize: 14,
    fontWeight: '700',
  },
  answerBinaryTextSelected: {
    color: '#FFF',
  },
  saveAnswerBtn: {
    backgroundColor: GOLD,
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 8,
  },
  saveAnswerBtnDisabled: {
    opacity: 0.55,
  },
  saveAnswerBtnText: {
    color: '#FFF',
    fontSize: 15,
    fontWeight: '800',
  },
  featureCard: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.06)',
  },
  featureCardBody: { flex: 1, marginHorizontal: 12, marginTop: 2, alignItems: 'flex-start' },
  featureCardTitle: {
    fontSize: 15,
    fontWeight: '900',
    color: NAVY,
    textAlign: 'left',
  },
  featureCardSub: {
    fontSize: 12,
    color: '#6F7782',
    marginTop: 4,
    textAlign: 'left',
  },
  featureIconCircle: {
    width: 50,
    height: 50,
    borderRadius: 16,
    backgroundColor: '#FFF8E5',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
