import { StyleSheet } from 'react-native';
import { BG, GOLD, NAVY } from './constants';
import { shadow } from '../shared/designTokens';
import { AppTheme } from '../../lib/nightMode';

const lightHomeColors: AppTheme['colors'] = {
  background: BG,
  card: '#FFFFFF',
  cardMuted: '#F8FAFD',
  header: NAVY,
  text: NAVY,
  mutedText: '#667085',
  border: '#E3E8F1',
  accent: GOLD,
  tabInactive: 'rgba(255,255,255,0.45)',
  shadow: '#000000',
};

export const createHomeStyles = (
  colors: AppTheme['colors'] = lightHomeColors,
) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.background,
    },
    topInset: { backgroundColor: colors.header },
    headerShell: {
      backgroundColor: colors.header,
      paddingHorizontal: 20,
      paddingTop: 12,
      paddingBottom: 18,
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
    },
    headerTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 10,
    },
    headerIdentity: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      marginRight: 12,
    },
    logoutBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(255,255,255,0.08)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.12)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarWrap: {
      width: 48,
      height: 48,
      marginRight: 12,
    },
    headerEyebrow: {
      color: '#E6D5A2',
      fontSize: 12,
      fontWeight: '700',
      textAlign: 'left',
      marginBottom: 2,
    },
    headerTitle: {
      color: '#FFF',
      fontSize: 20,
      lineHeight: 26,
      fontWeight: '800',
      textAlign: 'left',
    },
    headerTextBlock: {
      flex: 1,
    },
    headerCaptionCard: {
      borderWidth: 1,
      borderRadius: 16,
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    headerCaption: {
      color: 'rgba(255,255,255,0.68)',
      fontSize: 12,
      lineHeight: 19,
      textAlign: 'left',
    },
    avatar: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: '#78A1BD',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: 'rgba(255,255,255,0.16)',
    },
    avatarText: { color: '#FFF', fontSize: 16, fontWeight: '800' },
    scrollContent: { padding: 18, paddingBottom: 40, gap: 16 },
    quickActionsSection: {
      marginBottom: 2,
    },
    homeSectionTitle: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '900',
      textAlign: 'left',
      marginBottom: 10,
    },
    buttonsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
    },
    quickBtn: {
      width: '31%',
      backgroundColor: colors.card,
      borderRadius: 22,
      paddingVertical: 16,
      paddingHorizontal: 8,
      alignItems: 'center',
      minHeight: 112,
      justifyContent: 'center',
      ...shadow.soft,
    },
    quickIconWrap: {
      width: 48,
      height: 48,
      borderRadius: 16,
      backgroundColor: colors.cardMuted,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 10,
    },
    quickBtnText: {
      fontSize: 12,
      lineHeight: 17,
      fontWeight: '800',
      color: colors.text,
      textAlign: 'center',
    },
    questionCard: {
      backgroundColor: colors.header,
      borderRadius: 26,
      padding: 22,
      overflow: 'hidden',
      ...shadow.hero,
    },
    questionDecor: {
      position: 'absolute',
      top: -42,
      right: -30,
      width: 160,
      height: 160,
      borderRadius: 80,
      backgroundColor: 'rgba(120,161,189,0.16)',
    },
    questionTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    questionIconWrap: {
      width: 42,
      height: 42,
      borderRadius: 15,
      backgroundColor: 'rgba(255,255,255,0.1)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
    },
    questionCardLabel: {
      fontSize: 12,
      color: '#E6D5A2',
      fontWeight: '800',
      textAlign: 'left',
    },
    questionText: {
      fontSize: 19,
      fontWeight: '900',
      color: '#FFF',
      textAlign: 'left',
      marginBottom: 16,
      lineHeight: 29,
    },
    answerBtn: {
      backgroundColor: '#78A1BD',
      borderRadius: 18,
      minHeight: 54,
      alignItems: 'center',
      justifyContent: 'center',
    },
    answerBtnText: { color: '#FFF', fontSize: 16, fontWeight: '900' },
    answeredYesCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: '#2D9C5A',
      borderRadius: 14,
      paddingVertical: 12,
      paddingHorizontal: 16,
      justifyContent: 'center',
    },
    answeredYesText: {
      color: '#FFF',
      fontSize: 13,
      fontWeight: '600',
      textAlign: 'center',
      flex: 1,
    },
    answeredNoCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: '#E67E22',
      borderRadius: 14,
      paddingVertical: 12,
      paddingHorizontal: 16,
      justifyContent: 'center',
    },
    answeredNoText: {
      color: '#FFF',
      fontSize: 13,
      fontWeight: '600',
      textAlign: 'center',
      flex: 1,
    },
    answeredBlock: {
      gap: 10,
    },
    editAnswerBtn: {
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.24)',
      borderRadius: 14,
      paddingVertical: 10,
      alignItems: 'center',
    },
    editAnswerBtnText: {
      color: '#FFF',
      fontSize: 13,
      fontWeight: '900',
    },
    todayReadingCard: {
      backgroundColor: colors.card,
      borderRadius: 22,
      padding: 16,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      borderWidth: 1,
      borderColor: `${colors.accent}22`,
      ...shadow.soft,
    },
    todayReadingIconWrap: {
      width: 52,
      height: 52,
      borderRadius: 18,
      backgroundColor: `${colors.accent}14`,
      alignItems: 'center',
      justifyContent: 'center',
    },
    todayReadingBody: {
      flex: 1,
      minWidth: 0,
      alignItems: 'flex-start',
      gap: 4,
    },
    todayReadingEyebrow: {
      color: colors.accent,
      fontSize: 11,
      fontWeight: '800',
      textAlign: 'left',
      writingDirection: 'rtl',
    },
    todayReadingTitle: {
      color: colors.text,
      fontSize: 15,
      lineHeight: 23,
      fontWeight: '900',
      textAlign: 'left',
      writingDirection: 'rtl',
    },
    todayReadingSubtitle: {
      color: colors.mutedText,
      fontSize: 12,
      lineHeight: 18,
      fontWeight: '700',
      textAlign: 'left',
      writingDirection: 'rtl',
    },
    todayReadingAction: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.cardMuted,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sheetOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.45)',
      justifyContent: 'flex-end',
    },
    sheetBackdrop: {
      flex: 1,
    },
    answerSheet: {
      backgroundColor: colors.card,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      padding: 18,
      maxHeight: '80%',
    },
    answerSheetScrollContent: {
      paddingBottom: 4,
    },
    answerSheetTitle: {
      color: colors.text,
      fontSize: 19,
      fontWeight: '800',
      textAlign: 'left',
    },
    answerSheetSubtitle: {
      color: colors.mutedText,
      fontSize: 13,
      marginTop: 6,
      marginBottom: 14,
      textAlign: 'left',
    },
    answerSheetHint: {
      color: colors.mutedText,
      fontSize: 12,
      lineHeight: 18,
      marginTop: 12,
      marginBottom: 8,
      textAlign: 'left',
    },
    planTodayCard: {
      backgroundColor: colors.header,
      borderRadius: 16,
      padding: 14,
      marginTop: 14,
    },
    planTodayHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: 8,
    },
    planTodayEyebrow: {
      color: '#E6D5A2',
      fontSize: 12,
      fontWeight: '700',
      textAlign: 'left',
    },
    planTodayQuestion: {
      color: '#FFF',
      fontSize: 14,
      fontWeight: '700',
      textAlign: 'left',
    },
    planTodayLabel: {
      color: 'rgba(255,255,255,0.82)',
      fontSize: 13,
      marginTop: 4,
      textAlign: 'left',
    },
    planTodayBtn: {
      marginTop: 12,
      minHeight: 40,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: GOLD,
    },
    planTodayBtnApplied: {
      backgroundColor: 'rgba(255,255,255,0.18)',
    },
    planTodayBtnText: {
      color: '#FFF',
      fontSize: 14,
      fontWeight: '800',
    },
    readingEntriesBox: {
      gap: 8,
      marginTop: 10,
      marginBottom: 10,
    },
    readingEntryRow: {
      backgroundColor: colors.cardMuted,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 12,
      paddingVertical: 10,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    readingEntryText: {
      flex: 1,
      color: colors.text,
      fontSize: 13,
      fontWeight: '800',
      lineHeight: 18,
      textAlign: 'left',
    },
    readingEntryRemove: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: 'rgba(255,59,48,0.10)',
    },
    readingEntryRemoveText: {
      color: '#B42318',
      fontSize: 11,
      fontWeight: '900',
    },
    addReadingEntryBtn: {
      minHeight: 40,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 10,
      backgroundColor: '#78A1BD',
    },
    addReadingEntryBtnDisabled: {
      opacity: 0.55,
    },
    addReadingEntryText: {
      color: '#FFF',
      fontSize: 13,
      fontWeight: '900',
    },
    answerFieldTitle: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '700',
      marginBottom: 8,
      marginTop: 10,
      textAlign: 'left',
    },
    answerRangeHint: {
      color: colors.mutedText,
      fontSize: 12,
      lineHeight: 18,
      marginTop: -2,
      marginBottom: 8,
      textAlign: 'left',
    },
    answerGroupLabel: {
      color: colors.mutedText,
      fontSize: 12,
      fontWeight: '700',
      marginBottom: 6,
    },
    answerTestamentTabs: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 12,
      backgroundColor: colors.cardMuted,
      borderRadius: 18,
      padding: 6,
    },
    answerTestamentTab: {
      flex: 1,
      borderRadius: 14,
      paddingVertical: 10,
      paddingHorizontal: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    answerTestamentTabActive: {
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: 'rgba(10,17,36,0.06)',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 1,
    },
    answerTestamentTabText: {
      color: colors.mutedText,
      fontSize: 13,
      fontWeight: '700',
    },
    answerTestamentTabTextActive: {
      color: colors.text,
    },
    answerBookPanel: {
      backgroundColor: colors.cardMuted,
      borderRadius: 18,
      padding: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    answerBookPanelHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 10,
    },
    answerBookPanelTitle: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '800',
    },
    answerBookPanelCount: {
      color: colors.mutedText,
      fontSize: 12,
      fontWeight: '700',
    },
    answerChoiceRow: {
      gap: 8,
      paddingBottom: 8,
    },
    answerChoiceChip: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 999,
      paddingHorizontal: 14,
      paddingVertical: 8,
      backgroundColor: colors.card,
    },
    answerBookChoiceChip: {
      minHeight: 44,
      justifyContent: 'center',
      borderRadius: 14,
    },
    answerChoiceChipSelected: {
      borderColor: colors.header,
      backgroundColor: colors.header,
    },
    answerChoiceText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '600',
    },
    answerBookChoiceText: {
      textAlign: 'center',
    },
    answerRangeSummaryCard: {
      backgroundColor: colors.cardMuted,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginTop: 4,
    },
    answerRangeSummaryLabel: {
      color: colors.mutedText,
      fontSize: 12,
      fontWeight: '700',
      marginBottom: 4,
    },
    answerRangeSummaryValue: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '800',
    },
    answerChoiceTextSelected: {
      color: '#FFF',
    },
    answerBinaryRow: {
      flexDirection: 'row',
      gap: 10,
    },
    answerBinaryBtn: {
      flex: 1,
      borderRadius: 14,
      paddingVertical: 12,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      backgroundColor: colors.card,
    },
    answerBinaryBtnSelected: {
      backgroundColor: colors.header,
      borderColor: colors.header,
    },
    answerBinaryText: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '700',
    },
    answerBinaryTextSelected: {
      color: '#FFF',
    },
    saveAnswerBtn: {
      backgroundColor: '#78A1BD',
      borderRadius: 16,
      paddingVertical: 14,
      alignItems: 'center',
      marginTop: 16,
      marginBottom: 8,
    },
    saveAnswerBtnDisabled: {
      opacity: 0.55,
    },
    saveAnswerBtnText: {
      color: '#FFF',
      fontSize: 15,
      fontWeight: '800',
    },
    featureCard: {
      backgroundColor: colors.card,
      borderRadius: 20,
      padding: 16,
      flexDirection: 'row',
      alignItems: 'center',
      ...shadow.soft,
    },
    featureCardBody: {
      flex: 1,
      marginHorizontal: 14,
      marginTop: 2,
      alignItems: 'flex-start',
    },
    featureCardTitle: {
      fontSize: 15,
      fontWeight: '900',
      color: colors.text,
      textAlign: 'left',
    },
    featureCardSub: {
      fontSize: 12,
      color: colors.mutedText,
      marginTop: 4,
      textAlign: 'left',
      lineHeight: 18,
    },
    featureIconCircle: {
      width: 54,
      height: 54,
      borderRadius: 18,
      backgroundColor: '#78A1BD',
      justifyContent: 'center',
      alignItems: 'center',
    },
    featureChevron: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.cardMuted,
      alignItems: 'center',
      justifyContent: 'center',
    },
  });

export const homeStyles = createHomeStyles();
