import { Platform, StyleSheet } from 'react-native';

export const NAVY = '#0A1124';
export const GOLD = '#C9A84C';

export const spiritualReflectionStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F2F4F8' },
  topInset: { backgroundColor: NAVY },
  header: {
    backgroundColor: NAVY,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'android' ? 12 : 8,
    paddingBottom: 16,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addHeaderBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(201,168,76,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: '700',
    flex: 1,
    minWidth: 0,
    textAlign: 'center',
  },
  list: { padding: 16, paddingBottom: 32 },
  loader: { marginTop: 36 },
  card: {
    backgroundColor: '#FFF',
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
    elevation: 2,
    shadowColor: '#000',
    justifyContent: 'space-between',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 4,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  cardCompact: { padding: 12 },
  cardBody: { flex: 1, minWidth: 0 },
  cardHeader: {
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  dateRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  dateText: { color: '#888', fontSize: 12 },
  cardContent: {
    fontSize: 15,
    color: '#333',
    lineHeight: 24,
    textAlign: 'left',
  },
  actionGroup: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
    alignItems: 'center',
    marginLeft: 10,
    flexShrink: 0,
  },
  actionGroupCompact: { marginLeft: 6 },
  actionBtnCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFF',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    marginVertical: 6,
  },
  editBtn: {
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.06)',
    backgroundColor: '#0A1124',
  },
  trashBtn: {
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.06)',
    backgroundColor: '#FF3B30',
  },
  emptyContainer: { alignItems: 'center', marginTop: 60 },
  emptyIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(201,168,76,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    color: '#333',
    fontSize: 16,
    fontWeight: '600',
    marginTop: 16,
  },
  emptyTextSmall: {
    color: '#AAA',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 8,
    lineHeight: 22,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  modalOverlayTransparent: { backgroundColor: 'transparent' },
  modalBox: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 12,
    width: '100%',
    maxHeight: '90%',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: NAVY,
    textAlign: 'left',
  },
  modalHint: { color: '#888', fontSize: 13, marginTop: 4, textAlign: 'left' },
  modalBoxPadded: { paddingBottom: 8 },
  modalPressable: { position: 'absolute', inset: 0 },
  modalScrollArea: { marginTop: 8 },
  modalScrollContent: { paddingBottom: 20 },
  modalInput: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 12,
    padding: 14,
    fontSize: 15,
    color: '#333',
    minHeight: 160,
    marginTop: 12,
    textAlignVertical: 'top',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    marginTop: 12,
    flexWrap: 'wrap',
    paddingBottom: Platform.OS === 'ios' ? 8 : 16,
  },
  modalActionsCompact: {
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  cancelBtn: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 10,
    backgroundColor: '#F0F0F0',
    alignItems: 'center',
    marginBottom: 8,
  },
  cancelBtnText: { color: '#555', fontWeight: '600' },
  saveBtn: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 10,
    backgroundColor: '#0A1124',
    alignItems: 'center',
    marginBottom: 8,
  },
  saveBtnDisabled: { opacity: 0.6 },
  saveBtnText: { color: '#FFF', fontWeight: 'bold' },
  modalScroll: { flexGrow: 1, paddingBottom: 12 },
  flexOne: { flex: 1 },
  deleteBtn: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 10,
    backgroundColor: '#FF3B30',
    alignItems: 'center',
    marginBottom: 8,
  },
  deleteBtnText: { color: '#FFF', fontWeight: '700' },
});
