import { Platform, StyleSheet } from 'react-native';
import {
  heroBadgeBase,
  heroBadgeTextBase,
  heroCardBase,
  heroEyebrowBase,
  heroGlowBase,
  heroIconWrapBase,
  heroTextBase,
  heroTitleBase,
  heroTopRowBase,
} from '../shared/heroStyles';

export const NAVY = '#0A1124';
export const GOLD = '#78A1BD';

export const spiritualReflectionStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F2F4F8' },
  topInset: { backgroundColor: NAVY },
  header: {
    backgroundColor: NAVY,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'android' ? 12 : 8,
    paddingBottom: 16,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addHeaderBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(120,161,189,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: '700',
    flex: 1,
    minWidth: 0,
    textAlign: 'center',
  },
  list: { padding: 16, paddingBottom: 32 },
  loader: { marginTop: 36 },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 4,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.06)',
  },
  searchInput: {
    flex: 1,
    marginRight: 8,
    fontSize: 14,
    color: '#222',
    textAlign: 'right',
  },
  heroCard: {
    ...heroCardBase,
    marginBottom: 16,
  },
  heroGlow: {
    ...heroGlowBase,
  },
  heroTopRow: {
    ...heroTopRowBase,
    marginBottom: 12,
  },
  heroBadge: {
    ...heroBadgeBase,
  },
  heroBadgeText: {
    ...heroBadgeTextBase,
  },
  heroIconWrap: {
    ...heroIconWrapBase,
  },
  heroEyebrow: {
    ...heroEyebrowBase,
  },
  heroTitle: {
    ...heroTitleBase,
  },
  heroText: {
    ...heroTextBase,
    marginBottom: 16,
  },
  heroStatsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  heroStatCard: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    paddingVertical: 14,
    paddingHorizontal: 12,
  },
  heroStatNumber: {
    color: '#FFF',
    fontSize: 24,
    fontWeight: '800',
    marginBottom: 4,
    textAlign: 'left',
  },
  heroStatValue: {
    color: '#FFF',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 8,
    textAlign: 'left',
  },
  heroStatLabel: {
    color: 'rgba(255,255,255,0.64)',
    fontSize: 12,
    textAlign: 'left',
  },
  card: {
    backgroundColor: '#FFF',
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    elevation: 2,
    shadowColor: '#0A1124',
    justifyContent: 'space-between',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    flexDirection: 'row',
    alignItems: 'flex-start',
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.05)',
    overflow: 'hidden',
  },
  cardCompact: { padding: 12 },
  cardAccent: {
    position: 'absolute',
    top: 16,
    bottom: 16,
    left: 0,
    width: 4,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    backgroundColor: '#78A1BD',
  },
  cardBody: { flex: 1, minWidth: 0 },
  cardHeader: {
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  cardDatePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#FFF6E5',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  dateText: { color: NAVY, fontSize: 12, fontWeight: '700' },
  cardContent: {
    fontSize: 15,
    color: '#2F3642',
    lineHeight: 24,
    textAlign: 'left',
  },
  actionGroup: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
    alignItems: 'center',
    marginLeft: 10,
    flexShrink: 0,
  },
  actionGroupCompact: { marginLeft: 6 },
  actionBtnCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#FFF',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 0,
    marginVertical: 4,
  },
  editBtn: {
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.08)',
    backgroundColor: '#0A1124',
  },
  trashBtn: {
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.08)',
    backgroundColor: '#FF3B30',
  },
  emptyContainer: {
    alignItems: 'center',
    marginTop: 24,
    backgroundColor: '#FFF',
    borderRadius: 22,
    paddingHorizontal: 20,
    paddingVertical: 28,
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.05)',
  },
  emptyIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: 'rgba(120,161,189,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    color: NAVY,
    fontSize: 18,
    fontWeight: '700',
    marginTop: 16,
  },
  emptyTextSmall: {
    color: '#7D8592',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 8,
    lineHeight: 22,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  modalOverlayTransparent: { backgroundColor: 'transparent' },
  modalBox: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 12,
    width: '100%',
    maxHeight: '90%',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: NAVY,
    textAlign: 'left',
  },
  modalHint: { color: '#888', fontSize: 13, marginTop: 4, textAlign: 'left' },
  modalBoxPadded: { paddingBottom: 8 },
  modalPressable: { position: 'absolute', inset: 0 },
  modalScrollArea: { marginTop: 8 },
  modalScrollContent: { paddingBottom: 20 },
  modalInput: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 12,
    padding: 14,
    fontSize: 15,
    color: '#333',
    minHeight: 160,
    marginTop: 12,
    textAlignVertical: 'top',
    textAlign: 'left',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    marginTop: 12,
    flexWrap: 'wrap',
    paddingBottom: Platform.OS === 'ios' ? 8 : 16,
  },
  modalActionsCompact: {
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  cancelBtn: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 10,
    backgroundColor: '#F0F0F0',
    alignItems: 'center',
    marginBottom: 8,
  },
  cancelBtnText: { color: '#555', fontWeight: '600' },
  saveBtn: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 10,
    backgroundColor: '#0A1124',
    alignItems: 'center',
    marginBottom: 8,
  },
  saveBtnDisabled: { opacity: 0.6 },
  saveBtnText: { color: '#FFF', fontWeight: 'bold' },
  modalScroll: { flexGrow: 1, paddingBottom: 12 },
  flexOne: { flex: 1 },
  deleteBtn: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 10,
    backgroundColor: '#FF3B30',
    alignItems: 'center',
    marginBottom: 8,
  },
  deleteBtnText: { color: '#FFF', fontWeight: '700' },
});
