import { Platform, StyleSheet } from 'react-native';
import { BG, CARD, DANGER, NAVY } from './constants';
import {
  heroBadgeBase,
  heroBadgeTextBase,
  heroCardBase,
  heroEyebrowBase,
  heroGlowBase,
  heroIconWrapBase,
  heroTextBase,
  heroTitleBase,
  heroTopRowBase,
} from '../shared/heroStyles';

export const prayerNotesStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: BG },
  topInset: { backgroundColor: NAVY },
  header: {
    backgroundColor: NAVY,
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'android' ? 12 : 8,
    paddingBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerCenter: { flex: 1, minWidth: 0, alignItems: 'center' },
  title: { color: '#FFF', fontSize: 18, fontWeight: '700' },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 4,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.06)',
  },
  searchInput: { flex: 1, marginRight: 8, fontSize: 14, color: '#222' },
  loader: { marginTop: 36 },
  fullScreenLoader: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#F8F9FB',
  },
  list: { paddingHorizontal: 16, paddingBottom: 0 },
  listWithBottomPadding: { paddingHorizontal: 16, paddingBottom: 32 },
  heroCard: {
    ...heroCardBase,
    marginTop: 12,
    marginBottom: 16,
  },
  heroGlow: {
    ...heroGlowBase,
  },
  heroTopRow: {
    ...heroTopRowBase,
    marginBottom: 12,
  },
  heroBadge: {
    ...heroBadgeBase,
  },
  heroBadgeText: {
    ...heroBadgeTextBase,
  },
  heroIconWrap: {
    ...heroIconWrapBase,
  },
  heroEyebrow: {
    ...heroEyebrowBase,
  },
  heroTitle: {
    ...heroTitleBase,
  },
  heroText: {
    ...heroTextBase,
    marginBottom: 16,
  },
  heroStatsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  heroStatCard: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    paddingVertical: 14,
    paddingHorizontal: 12,
  },
  heroStatNumber: {
    color: '#FFF',
    fontSize: 24,
    fontWeight: '800',
    marginBottom: 4,
    textAlign: 'left',
  },
  heroStatLabel: {
    color: 'rgba(255,255,255,0.64)',
    fontSize: 12,
    textAlign: 'left',
  },
  card: {
    backgroundColor: '#FFF',
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
    elevation: 2,
    shadowColor: '#0A1124',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.05)',
    overflow: 'hidden',
  },
  cardCompact: { padding: 12 },
  answeredCard: { opacity: 0.7 },
  cardAccent: {
    position: 'absolute',
    top: 16,
    bottom: 16,
    left: 0,
    width: 4,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    backgroundColor: '#C9A84C',
  },
  cardAccentAnswered: {
    backgroundColor: '#2D9C5A',
  },
  cardLeft: {
    width: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF6E5',
  },
  checkWrapAnswered: {
    backgroundColor: 'rgba(45,156,90,0.12)',
  },
  cardBody: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 8,
  },
  cardDatePill: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#FFF6E5',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginBottom: 10,
  },
  cardDateText: {
    color: NAVY,
    fontSize: 12,
    fontWeight: '700',
  },
  cardText: {
    fontSize: 15,
    color: '#2F3642',
    lineHeight: 24,
    textAlign: 'left',
  },
  cardActions: {
    flexDirection: 'row',
    gap: 8,
    flexShrink: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginLeft: 8,
  },
  cardActionsCompact: { marginLeft: 4 },
  iconBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#FFF',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 0,
  },
  quickAddWrap: {
    position: 'absolute',
    left: 16,
    right: 16,
    alignItems: 'center',
    backgroundColor: CARD,
    borderRadius: 14,
    padding: 8,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
  },
  editBanner: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 6,
    paddingBottom: 6,
  },
  editBannerText: {
    color: NAVY,
    fontSize: 13,
    textAlign: 'left',
    fontWeight: '700',
  },
  quickInputWrap: { width: '100%', marginBottom: 8 },
  quickInput: { maxHeight: 90, fontSize: 14, color: '#222' },
  quickActions: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  secondaryFab: {
    width: 42,
    height: 42,
    borderRadius: 26,
    backgroundColor: '#F1F3F6',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  secondaryFabDisabled: { opacity: 0.6 },
  fab: {
    width: 42,
    height: 42,
    borderRadius: 26,
    backgroundColor: NAVY,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fabDisabled: { opacity: 0.6 },
  sendIcon: { transform: [{ rotate: '180deg' }] },
  emptyWrap: { alignItems: 'center', marginTop: 60 },
  emptyContainer: {
    alignItems: 'center',
    marginHorizontal: 16,
    marginTop: 24,
    backgroundColor: '#FFF',
    borderRadius: 22,
    paddingHorizontal: 20,
    paddingVertical: 28,
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.05)',
  },
  emptyIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: 'rgba(201,168,76,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: { color: NAVY, fontSize: 18, marginTop: 16, fontWeight: '700' },
  emptyTextSmall: {
    color: '#7D8592',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 8,
    lineHeight: 22,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  modalBox: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 12,
    width: '100%',
    maxHeight: '90%',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: NAVY,
    textAlign: 'left',
  },
  modalHint: {
    color: '#888',
    fontSize: 13,
    marginTop: 4,
    textAlign: 'left',
  },
  detailActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginTop: 12,
    paddingBottom: Platform.OS === 'ios' ? 12 : 16,
  },
  detailActionsCompact: {
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    marginTop: 12,
    flexWrap: 'wrap',
    paddingBottom: Platform.OS === 'ios' ? 8 : 16,
  },
  cancelBtn: {
    flex: 1,
    minWidth: 0,
    marginHorizontal: 4,
    marginBottom: 8,
    backgroundColor: '#F0F0F0',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelBtnText: {
    color: '#555',
    fontWeight: '500',
    flex: 1,
  },
  secondaryBtn: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 10,
    backgroundColor: '#F0F0F0',
    alignItems: 'center',
    marginBottom: 8,
  },
  saveBtn: {
    flex: 1,
    minWidth: 0,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 28,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 4,
    marginBottom: 8,
    backgroundColor: '#0A1124',
  },
  saveBtnText: {
    color: '#FFF',
    fontWeight: 'bold',
  },
  dangerBtn: { backgroundColor: DANGER },
  modalOverlayTransparent: { backgroundColor: 'transparent' },
  modalPressable: { position: 'absolute', inset: 0 },
  modalBoxPadded: { paddingBottom: 8 },
  modalScroll: { flexGrow: 1, paddingBottom: 12 },
  modalScrollArea: { marginTop: 8 },
  modalScrollContent: { paddingBottom: 20 },
  modalInput: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 12,
    padding: 14,
    fontSize: 15,
    color: '#333',
    minHeight: 160,
    marginTop: 12,
    textAlignVertical: 'top',
  },
  saveBtnDisabled: { opacity: 0.6 },
  flexOne: { flex: 1 },
  saveBtnPrimary: { backgroundColor: NAVY },
  saveBtnTextLight: { color: '#FFF' },
  dangerBtnText: { color: '#FFF', fontWeight: '700' },
  deleteBtn: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 10,
    backgroundColor: '#FF3B30',
    alignItems: 'center',
    marginBottom: 8,
  },
  deleteBtnText: { color: '#FFF', fontWeight: '700' },
  answeredIconBtn: {
    borderColor: '#fff',
    backgroundColor: '#fff',
  },
  neutralIconBtn: {
    borderColor: 'rgba(10,17,36,0.06)',
  },
  editIconBtn: { backgroundColor: NAVY },
  deleteIconBtn: { backgroundColor: DANGER },
});
