import { Platform, StyleSheet } from 'react-native';
import { BG, CARD, DANGER, MUTED, NAVY } from './constants';

export const prayerNotesStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: BG },
  topInset: { backgroundColor: NAVY },
  header: {
    backgroundColor: NAVY,
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'android' ? 12 : 8,
    paddingBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerCenter: { flex: 1, minWidth: 0, alignItems: 'center' },
  title: { color: '#FFF', fontSize: 18, fontWeight: '700' },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: CARD,
    margin: 16,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    elevation: 1,
  },
  searchInput: { flex: 1, marginRight: 8, fontSize: 14, color: '#222' },
  loader: { marginTop: 36 },
  list: { paddingHorizontal: 16, paddingBottom: 120 },
  card: {
    backgroundColor: CARD,
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
    flexDirection: 'row',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
  },
  cardCompact: { padding: 12 },
  answeredCard: { opacity: 0.7 },
  cardLeft: { width: 44, alignItems: 'center', justifyContent: 'center' },
  checkWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardBody: { flex: 1, minWidth: 0, paddingHorizontal: 8 },
  cardText: {
    fontSize: 15,
    color: '#111',
    textAlign: 'left',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardActions: {
    flexDirection: 'row',
    gap: 8,
    flexShrink: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginLeft: 8,
  },
  cardActionsCompact: { marginLeft: 4 },
  iconBtn: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: '#FFF',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 0,
  },
  quickAddWrap: {
    position: 'absolute',
    left: 16,
    right: 16,
    alignItems: 'center',
    backgroundColor: CARD,
    borderRadius: 14,
    padding: 8,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
  },
  editBanner: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 6,
    paddingBottom: 6,
  },
  editBannerText: {
    color: NAVY,
    fontSize: 13,
    textAlign: 'left',
    fontWeight: '700',
  },
  quickInputWrap: { width: '100%', marginBottom: 8 },
  quickInput: { maxHeight: 90, fontSize: 14, color: '#222' },
  quickActions: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  secondaryFab: {
    width: 42,
    height: 42,
    borderRadius: 26,
    backgroundColor: '#F1F3F6',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  secondaryFabDisabled: { opacity: 0.6 },
  fab: {
    width: 42,
    height: 42,
    borderRadius: 26,
    backgroundColor: NAVY,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fabDisabled: { opacity: 0.6 },
  sendIcon: { transform: [{ rotate: '180deg' }] },
  emptyWrap: { alignItems: 'center', marginTop: 60 },
  emptyTitle: { color: MUTED, fontSize: 16, marginTop: 12, fontWeight: '700' },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  modalBox: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 12,
    width: '100%',
    maxHeight: '90%',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: NAVY,
    textAlign: 'left',
  },
  detailActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginTop: 12,
    paddingBottom: Platform.OS === 'ios' ? 12 : 16,
  },
  detailActionsCompact: {
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  cancelBtn: {
    flex: 1,
    minWidth: 0,
    backgroundColor: '#F0F0F0',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 4,
    marginBottom: 8,
  },
  cancelBtnText: {
    color: '#555',
    fontWeight: '500',
  },
  saveBtn: {
    flex: 1,
    minWidth: 0,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 4,
    marginBottom: 8,
  },
  saveBtnText: {
    fontWeight: '500',
  },
  dangerBtn: { backgroundColor: DANGER },
  modalOverlayTransparent: { backgroundColor: 'transparent' },
  modalPressable: { position: 'absolute', inset: 0 },
  modalBoxPadded: { paddingBottom: 8 },
  modalScroll: { marginTop: 8 },
  modalScrollContent: { paddingBottom: 20 },
  saveBtnPrimary: { backgroundColor: NAVY },
  saveBtnTextLight: { color: '#FFF' },
  dangerBtnText: { color: '#FFF', fontWeight: '700' },
  answeredIconBtn: {
    borderColor: '#fff',
    backgroundColor: '#fff',
  },
  neutralIconBtn: {
    borderColor: 'rgba(10,17,36,0.06)',
  },
  editIconBtn: { backgroundColor: NAVY },
  deleteIconBtn: { backgroundColor: DANGER },
});
