import { StyleSheet } from 'react-native';
import { AppTheme } from '../../lib/nightMode';
import { GOLD, NAVY } from '../shared/designTokens';

export { GOLD, NAVY };

export const createWeeklyReportStyles = (colors: AppTheme['colors']) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.background,
    },
    loadingText: {
      marginTop: 12,
      fontSize: 14,
      color: colors.mutedText,
    },
    content: { padding: 16, paddingBottom: 40 },
    rangePill: {
      alignSelf: 'center',
      backgroundColor: `${colors.accent}1F`,
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 999,
      marginBottom: 16,
    },
    rangePillText: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: '700',
    },
    encouragementCard: {
      backgroundColor: colors.header,
      borderRadius: 20,
      padding: 20,
      marginBottom: 18,
      flexDirection: 'row',
      alignItems: 'center',
    },
    encouragementIcon: {
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: 'rgba(255,255,255,0.12)',
      alignItems: 'center',
      justifyContent: 'center',
      marginLeft: 14,
    },
    encouragementText: {
      flex: 1,
      color: '#FFF',
      fontSize: 15,
      lineHeight: 24,
      fontWeight: '700',
      textAlign: 'center',
    },
    grid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
    },
    statCard: {
      width: '48.5%',
      backgroundColor: colors.card,
      borderRadius: 18,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 6,
      textAlign: 'center',
      alignItems: 'center',
      elevation: 2,
    },
    statIconCircle: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 12,
    },
    statValue: {
      fontSize: 24,
      fontWeight: '800',
      color: colors.text,
      textAlign: 'center',
    },
    statLabel: {
      fontSize: 13,
      color: colors.mutedText,
      marginTop: 4,
      textAlign: 'center',
    },
    emptyCard: {
      backgroundColor: colors.card,
      borderRadius: 18,
      padding: 24,
      marginBottom: 18,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
    },
    emptyTitle: {
      fontSize: 16,
      fontWeight: '800',
      color: colors.text,
      marginTop: 12,
      textAlign: 'center',
    },
    emptyMessage: {
      fontSize: 14,
      color: colors.mutedText,
      marginTop: 6,
      lineHeight: 22,
      textAlign: 'center',
    },
    shareButton: {
      marginTop: 6,
      backgroundColor: colors.accent,
      borderRadius: 16,
      paddingVertical: 15,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    shareButtonText: {
      color: '#FFF',
      fontSize: 15,
      fontWeight: '800',
      marginRight: 8,
    },
  });
