import { StyleSheet } from 'react-native';
import { AppTheme } from '../../lib/nightMode';
import { palette, radius, shadow, spacing } from '../shared/designTokens';

export const createStyles = (colors: AppTheme['colors']) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor:
        colors.background === palette.bg ? '#FFF' : colors.background,
    },
    content: {
      padding: spacing.lg,
      paddingBottom: 120,
      gap: spacing.lg,
    },
    readerActionsOverlay: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      zIndex: 20,
      elevation: 20,
      alignItems: 'flex-end',
    },
    readerActionsBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'transparent',
    },
    readerActionsMenu: {
      ...shadow.card,
      marginTop: 96,
      marginRight: spacing.lg,
      width: 258,
      borderRadius: radius.md,
      borderTopRightRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.card,
      overflow: 'hidden',
    },
    readerActionRow: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      paddingHorizontal: spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    readerActionRowActive: {
      backgroundColor: `${palette.accent}14`,
    },
    readerActionText: {
      flex: 1,
      color: colors.text,
      fontSize: 14,
      fontWeight: '900',
      textAlign: 'left',
      writingDirection: 'rtl',
    },
    selectionHero: {
      ...shadow.card,
      alignItems: 'center',
      gap: spacing.md,
      backgroundColor: colors.header,
      borderRadius: radius.xl,
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.xl,
    },
    selectionHeroIcon: {
      width: 56,
      height: 56,
      borderRadius: 20,
      backgroundColor: colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
    },
    selectionHeroTitle: {
      color: '#FFF',
      fontSize: 20,
      fontWeight: '900',
      textAlign: 'center',
      writingDirection: 'rtl',
    },
    selectionHeroSubtitle: {
      color: 'rgba(255,255,255,0.72)',
      fontSize: 13,
      lineHeight: 21,
      fontWeight: '700',
      textAlign: 'center',
      writingDirection: 'rtl',
    },
    currentReadingCard: {
      ...shadow.card,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
      backgroundColor: colors.card,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: colors.border,
      padding: spacing.md,
    },
    currentReadingIcon: {
      width: 42,
      height: 42,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.header,
    },
    currentReadingText: {
      flex: 1,
      minWidth: 0,
      alignItems: 'flex-start',
    },
    currentReadingLabel: {
      color: colors.mutedText,
      fontSize: 11,
      fontWeight: '800',
      textAlign: 'left',
      writingDirection: 'rtl',
      marginBottom: 3,
    },
    currentReadingTitle: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '900',
      textAlign: 'left',
      writingDirection: 'rtl',
    },
    chapterNavCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      paddingVertical: spacing.xs,
    },
    chapterNavButton: {
      minWidth: 82,
      minHeight: 46,
      borderRadius: 16,
      backgroundColor: colors.header,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 2,
      paddingHorizontal: spacing.sm,
    },
    chapterNavButtonDisabled: {
      backgroundColor: colors.cardMuted,
    },
    chapterNavButtonText: {
      color: '#FFF',
      fontSize: 13,
      fontWeight: '900',
      textAlign: 'center',
      writingDirection: 'rtl',
    },
    chapterNavButtonTextDisabled: {
      color: colors.mutedText,
    },
    chapterNavCurrent: {
      flex: 1,
      minWidth: 0,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing.xs,
    },
    chapterNavCurrentValue: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 2,
    },
    chapterNavCurrentLabel: {
      color: colors.mutedText,
      fontSize: 10,
      fontWeight: '800',
      textAlign: 'center',
      writingDirection: 'rtl',
      marginBottom: 2,
    },
    chapterNavCurrentText: {
      color: colors.text,
      fontSize: 13,
      lineHeight: 20,
      fontWeight: '900',
      textAlign: 'center',
      writingDirection: 'rtl',
    },
    chapterNavCurrentChevron: {
      lineHeight: 18,
      transform: [{ translateY: 2 }],
    },
    searchModalOverlay: {
      flex: 1,
      justifyContent: 'center',
      padding: spacing.lg,
    },
    searchModalBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(10,17,36,0.42)',
    },
    searchPanel: {
      ...shadow.card,
      backgroundColor: colors.card,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: colors.border,
      padding: spacing.lg,
      gap: spacing.md,
      maxHeight: '78%',
    },
    searchHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.md,
    },
    searchTitle: {
      flex: 1,
      color: colors.text,
      fontSize: 17,
      fontWeight: '900',
      textAlign: 'left',
      writingDirection: 'rtl',
    },
    searchCloseButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.cardMuted,
    },
    searchInputRow: {
      minHeight: 48,
      borderRadius: 16,
      backgroundColor: colors.cardMuted,
      paddingHorizontal: spacing.md,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
    },
    searchInput: {
      flex: 1,
      minWidth: 0,
      color: colors.text,
      fontSize: 15,
      fontWeight: '800',
      writingDirection: 'rtl',
      paddingVertical: 0,
    },
    searchMeta: {
      color: colors.mutedText,
      fontSize: 12,
      fontWeight: '800',
      textAlign: 'left',
      writingDirection: 'rtl',
    },
    searchResults: {
      gap: spacing.sm,
      paddingBottom: spacing.xs,
    },
    searchResultsScroll: {
      maxHeight: 360,
    },
    searchResultRow: {
      backgroundColor: colors.cardMuted,
      borderRadius: 14,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      gap: 4,
    },
    searchResultRef: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: '900',
      textAlign: 'left',
      writingDirection: 'rtl',
    },
    searchResultText: {
      color: colors.text,
      fontSize: 13,
      lineHeight: 20,
      fontWeight: '700',
      textAlign: 'left',
      writingDirection: 'rtl',
    },
    savedVerseMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.sm,
    },
    savedSection: {
      gap: spacing.sm,
    },
    savedSectionTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '900',
      textAlign: 'left',
      writingDirection: 'rtl',
      marginTop: spacing.xs,
    },
    savedSectionEmpty: {
      color: colors.mutedText,
      fontSize: 12,
      fontWeight: '800',
      textAlign: 'left',
      writingDirection: 'rtl',
      backgroundColor: colors.cardMuted,
      borderRadius: 12,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
    },
    savedVerseBadges: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.xs,
    },
    savedVerseColorDot: {
      width: 16,
      height: 16,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    emptySavedVersesText: {
      color: colors.mutedText,
      fontSize: 14,
      lineHeight: 22,
      fontWeight: '800',
      textAlign: 'center',
      writingDirection: 'rtl',
      paddingVertical: spacing.xl,
    },
    selectionToolbar: {
      backgroundColor: colors.card,
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: colors.border,
      padding: spacing.md,
      gap: spacing.sm,
    },
    selectionToolbarHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.md,
    },
    selectionToolbarTitle: {
      flex: 1,
      color: colors.text,
      fontSize: 14,
      fontWeight: '900',
      textAlign: 'left',
      writingDirection: 'rtl',
    },
    selectionToolbarIconButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.cardMuted,
    },
    selectionToolbarActions: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: spacing.sm,
    },
    selectionActionButton: {
      minHeight: 38,
      borderRadius: 14,
      paddingHorizontal: spacing.md,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.xs,
      backgroundColor: colors.cardMuted,
    },
    selectionActionText: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '900',
      textAlign: 'left',
      writingDirection: 'rtl',
    },
    highlightSwatches: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.xs,
    },
    highlightSwatch: {
      width: 30,
      height: 30,
      borderRadius: 15,
      borderWidth: 1,
      borderColor: colors.border,
    },
    pickerCard: {
      ...shadow.card,
      backgroundColor: colors.card,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: colors.border,
      padding: spacing.lg,
      gap: spacing.md,
    },
    pickerHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
      paddingBottom: spacing.sm,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    pickerIcon: {
      width: 40,
      height: 40,
      borderRadius: 15,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.accent,
    },
    pickerHeaderText: { flex: 1, minWidth: 0 },
    pickerTitle: {
      color: colors.text,
      fontSize: 17,
      fontWeight: '900',
      textAlign: 'left',
      writingDirection: 'rtl',
      marginBottom: 3,
    },
    pickerSubtitle: {
      color: colors.mutedText,
      fontSize: 12,
      fontWeight: '700',
      textAlign: 'left',
      writingDirection: 'rtl',
    },
    stepHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
    },
    stepBadge: {
      width: 26,
      height: 26,
      borderRadius: 13,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: `${palette.accent}24`,
      borderWidth: 1,
      borderColor: `${palette.accent}44`,
    },
    stepBadgeText: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: '900',
    },
    stepTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '900',
      textAlign: 'left',
    },
    dropdownTrigger: {
      minHeight: 56,
      borderRadius: 18,
      backgroundColor: colors.cardMuted,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: spacing.md,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.md,
    },
    dropdownTriggerOpen: {
      borderColor: colors.accent,
      backgroundColor: `${palette.accent}14`,
    },
    dropdownValueBlock: {
      flex: 1,
      alignItems: 'flex-start',
    },
    dropdownValue: {
      flex: 1,
      color: colors.text,
      fontSize: 15,
      fontWeight: '900',
      textAlign: 'left',
      writingDirection: 'rtl',
    },
    dropdownMeta: {
      color: colors.mutedText,
      fontSize: 11,
      fontWeight: '800',
      marginTop: 3,
      textAlign: 'left',
      writingDirection: 'rtl',
    },
    dropdownMenu: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.card,
      overflow: 'hidden',
    },
    dropdownScroll: {
      maxHeight: 260,
    },
    dropdownOption: {
      minHeight: 50,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    dropdownOptionActive: {
      backgroundColor: `${palette.accent}14`,
    },
    optionTextBlock: {
      flex: 1,
      minWidth: 0,
      alignItems: 'flex-start',
    },
    dropdownOptionText: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '900',
      textAlign: 'left',
      writingDirection: 'rtl',
    },
    dropdownOptionTextActive: {
      color: colors.accent,
    },
    dropdownOptionMeta: {
      color: colors.mutedText,
      fontSize: 11,
      fontWeight: '800',
      marginTop: 3,
      textAlign: 'left',
      writingDirection: 'rtl',
    },
    chapterDropdownMenu: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.card,
      padding: spacing.sm,
    },
    chapterOption: {
      width: 42,
      height: 42,
      borderRadius: 15,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.cardMuted,
      borderWidth: 1,
      borderColor: colors.border,
    },
    chapterOptionActive: {
      backgroundColor: colors.header,
      borderColor: colors.header,
    },
    chapterOptionText: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '900',
    },
    chapterOptionTextActive: {
      color: '#FFF',
    },
    startReadingButton: {
      minHeight: 54,
      borderRadius: 18,
      backgroundColor: colors.header,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.sm,
      marginTop: spacing.sm,
    },
    startReadingText: {
      color: '#FFF',
      fontSize: 15,
      fontWeight: '900',
      textAlign: 'left',
      writingDirection: 'rtl',
    },
    readerCard: {
      paddingVertical: spacing.sm,
      gap: spacing.md,
    },
    readerCardParallel: {
      paddingVertical: spacing.sm,
    },
    parallelHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      paddingHorizontal: spacing.sm,
      paddingBottom: spacing.xs,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    parallelHeaderSpacer: {
      width: 28,
    },
    parallelHeaderColumns: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      gap: spacing.sm,
    },
    parallelHeaderText: {
      flex: 1,
      minWidth: 0,
      color: colors.accent,
      fontSize: 12,
      fontWeight: '900',
      textAlign: 'center',
      writingDirection: 'rtl',
    },
    readerHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.md,
      paddingBottom: spacing.sm,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    readerEyebrow: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: '800',
      textAlign: 'left',
      marginBottom: 3,
    },
    readerTitle: {
      color: colors.text,
      fontSize: 20,
      fontWeight: '900',
      textAlign: 'left',
    },
    readerBadge: {
      backgroundColor: `${palette.accent}24`,
      borderRadius: radius.pill,
      paddingHorizontal: spacing.md,
      paddingVertical: 7,
    },
    readerBadgeText: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: '900',
    },
    verseBlock: {
      gap: spacing.sm,
    },
    parallelVerseBlock: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: spacing.sm,
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.xs,
      position: 'relative',
    },
    parallelVerseNumber: {
      width: 28,
      minHeight: 42,
      alignItems: 'center',
      justifyContent: 'flex-start',
      gap: 2,
      marginTop: 2,
    },
    parallelColumns: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      gap: spacing.sm,
    },
    parallelColumn: {
      flex: 1,
      minWidth: 0,
      paddingHorizontal: spacing.xs,
    },
    verseRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: spacing.sm,
      borderRadius: 16,
      padding: spacing.xs,
      marginHorizontal: -spacing.xs,
      position: 'relative',
    },
    verseRowActive: {
      backgroundColor: `${palette.accent}12`,
    },
    selectedVerseForAction: {
      borderWidth: 2,
      borderColor: colors.accent,
    },
    selectedVerseCheck: {
      position: 'absolute',
      top: 4,
      right: 4,
      width: 20,
      height: 20,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.accent,
      borderWidth: 2,
      borderColor: colors.card,
      zIndex: 2,
    },
    verseNumber: {
      width: 28,
      height: 28,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 1,
    },
    verseNumberText: {
      color: colors.accent,
      fontSize: 11,
      fontWeight: '900',
    },
    verseText: {
      flex: 1,
      color: colors.text,
      fontSize: 17,
      lineHeight: 31,
      fontWeight: '600',
      textAlign: 'left',
      writingDirection: 'rtl',
    },
    lifeTranslationCard: {
      marginLeft: 36,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: `${palette.accent}33`,
      backgroundColor: `${palette.accent}10`,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      gap: 5,
    },
    inlineLifeTranslation: {
      marginLeft: 36,
      borderRadius: 16,
      backgroundColor: `${palette.accent}12`,
      borderWidth: 1,
      borderColor: `${palette.accent}33`,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      gap: 5,
    },
    inlineLifeTranslationLabel: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: '900',
      textAlign: 'left',
      writingDirection: 'rtl',
    },
    inlineLifeTranslationText: {
      color: colors.text,
      fontSize: 15,
      lineHeight: 25,
      fontWeight: '700',
      textAlign: 'left',
      writingDirection: 'rtl',
    },
    lifeTranslationLabel: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: '900',
      textAlign: 'left',
      writingDirection: 'rtl',
    },
    lifeTranslationText: {
      color: colors.text,
      fontSize: 15,
      lineHeight: 25,
      fontWeight: '700',
      textAlign: 'left',
      writingDirection: 'rtl',
    },
    wordMeaningsCard: {
      marginLeft: 36,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: `${palette.accent}33`,
      backgroundColor: colors.cardMuted,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      gap: spacing.sm,
    },
    wordMeaningItem: {
      borderTopWidth: 1,
      borderTopColor: colors.border,
      paddingTop: spacing.sm,
      gap: 3,
    },
    wordMeaningTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '900',
      textAlign: 'left',
      writingDirection: 'rtl',
    },
    wordMeaningOriginal: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: '800',
      textAlign: 'left',
    },
    wordMeaningText: {
      color: colors.mutedText,
      fontSize: 13,
      lineHeight: 20,
      fontWeight: '700',
      textAlign: 'left',
      writingDirection: 'rtl',
    },

    // ─── Selection Bar (bottom sheet) ───
    selectionBar: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: colors.card,
      borderTopLeftRadius: radius.lg,
      borderTopRightRadius: radius.lg,
      borderWidth: 1,
      borderBottomWidth: 0,
      borderColor: colors.border,
      paddingHorizontal: spacing.md,
      paddingTop: spacing.xs,
      gap: spacing.xs,
      shadowColor: '#0A1124',
      shadowOpacity: 0.14,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: -6 },
      elevation: 12,
    },
    selectionBarHandle: {
      alignSelf: 'center',
      width: 32,
      height: 3,
      borderRadius: 2,
      backgroundColor: colors.border,
      marginBottom: 2,
    },
    selectionBarTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    selectionBarInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
    },
    selectionBarCountBadge: {
      minWidth: 24,
      height: 24,
      paddingHorizontal: 6,
      borderRadius: 12,
      backgroundColor: colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
    },
    selectionBarCountText: {
      color: '#FFF',
      fontSize: 12,
      fontWeight: '900',
    },
    selectionBarLabel: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '900',
      writingDirection: 'rtl',
    },
    selectionBarCloseBtn: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: colors.cardMuted,
      alignItems: 'center',
      justifyContent: 'center',
    },
    selectionBarActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.xs,
      paddingVertical: 2,
      paddingRight: spacing.xs,
    },
    selectionChip: {
      width: 64,
      alignItems: 'center',
      justifyContent: 'flex-start',
      gap: 4,
      paddingVertical: 2,
    },
    selectionChipIcon: {
      width: 40,
      height: 40,
      borderRadius: 13,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: `${palette.accent}14`,
      borderWidth: 1,
      borderColor: `${palette.accent}26`,
    },
    selectionChipIconGold: {
      backgroundColor: `${palette.gold}1F`,
      borderColor: `${palette.gold}40`,
    },
    selectionChipText: {
      color: colors.text,
      fontSize: 10,
      fontWeight: '800',
      textAlign: 'center',
      writingDirection: 'rtl',
    },
    selectionBarDivider: {
      width: 1,
      height: 40,
      backgroundColor: colors.border,
      marginHorizontal: spacing.xs,
      alignSelf: 'center',
    },
    selectionHighlightSection: {
      gap: 2,
      paddingTop: 2,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    selectionHighlightLabel: {
      color: colors.text,
      fontSize: 11,
      fontWeight: '900',
      writingDirection: 'rtl',
      textAlign: 'left',
    },
    selectionHighlightScrollWrap: {
      position: 'relative',
      marginHorizontal: -spacing.md,
      paddingLeft: spacing.md,
    },
    selectionHighlightScrollContent: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.xs,
      paddingRight: spacing.lg,
      paddingVertical: 2,
    },
    selectionHighlightFade: {
      position: 'absolute',
      left: 0,
      top: 0,
      bottom: 0,
      width: 28,
    },
    selectionHighlightGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      paddingTop: spacing.xs,
    },
    selectionBarSwatch: {
      width: 34,
      height: 34,
      borderRadius: 17,
      borderWidth: 1.5,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    selectionBarSwatchActive: {
      borderWidth: 2.5,
      borderColor: colors.text,
    },
    selectionEraser: {
      width: 36,
      height: 36,
      borderRadius: 13,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.cardMuted,
      borderWidth: 1,
      borderColor: colors.border,
    },
  });
