import { StyleSheet } from 'react-native';
import {
  heroBadgeBase,
  heroBadgeTextBase,
  heroCardBase,
  heroGlowBase,
  heroIconWrapBase,
  heroTextBase,
  heroTitleBase,
  heroTopRowBase,
  heroEyebrowBase,
} from '../shared/heroStyles';

export const NAVY = '#0A1124';
export const GOLD = '#C9A84C';
export const BG = '#F2F4F8';

export const devotionCalendarStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: BG },
  topInset: { backgroundColor: NAVY },
  header: {
    backgroundColor: NAVY,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 18,
  },
  backBtn: { padding: 4 },
  headerTitle: { color: '#FFF', fontSize: 18, fontWeight: '700' },
  headerSpacer: { width: 32 },
  loadingWrap: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  content: { padding: 16, paddingBottom: 36 },
  heroCard: {
    ...heroCardBase,
    marginBottom: 14,
  },
  heroGlow: {
    ...heroGlowBase,
  },
  heroTopRow: {
    ...heroTopRowBase,
    marginBottom: 14,
  },
  heroIconWrap: {
    ...heroIconWrapBase,
  },
  heroBadge: {
    ...heroBadgeBase,
  },
  heroBadgeText: {
    ...heroBadgeTextBase,
  },
  heroLabel: {
    ...heroEyebrowBase,
  },
  heroTitle: {
    ...heroTitleBase,
  },
  heroText: {
    ...heroTextBase,
  },
  heroHintRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 14,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.08)',
  },
  heroHintText: {
    flex: 1,
    color: 'rgba(255,255,255,0.84)',
    fontSize: 12,
    lineHeight: 18,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#FFF',
    borderRadius: 18,
    paddingVertical: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.06)',
    paddingHorizontal: 8,
  },
  statIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  statIconWrapPrimary: {
    backgroundColor: NAVY,
  },
  statIconWrapGold: {
    backgroundColor: '#FFF2CD',
  },
  statIconWrapSoft: {
    backgroundColor: '#E9EEF8',
  },
  statNumber: {
    color: NAVY,
    fontSize: 26,
    fontWeight: '800',
    marginBottom: 4,
  },
  statLabel: {
    color: '#79808A',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  calendarCard: {
    backgroundColor: '#FFF',
    borderRadius: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.06)',
    shadowColor: NAVY,
    shadowOpacity: 0.05,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  sectionTitle: {
    color: NAVY,
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 4,
  },
  sectionCaption: {
    color: '#7A818B',
    fontSize: 13,
  },
  sectionIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: '#F4F6FA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  monthHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    backgroundColor: '#F6F8FC',
    borderRadius: 18,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  monthNavBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: '#FFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.06)',
  },
  monthTitle: {
    color: NAVY,
    fontSize: 18,
    fontWeight: '800',
  },
  legendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
    paddingHorizontal: 2,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  legendSwatch: {
    width: 12,
    height: 12,
    borderRadius: 4,
  },
  legendSwatchCompleted: {
    backgroundColor: 'rgba(201,168,76,0.32)',
    borderWidth: 1,
    borderColor: 'rgba(201,168,76,0.48)',
  },
  legendSwatchToday: {
    backgroundColor: '#EEF3FF',
    borderWidth: 1.5,
    borderColor: NAVY,
  },
  legendSwatchDefault: {
    backgroundColor: '#F6F8FB',
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.06)',
  },
  legendText: {
    color: '#6F7782',
    fontSize: 12,
    fontWeight: '600',
  },
  weekRow: {
    flexDirection: 'row',
    marginBottom: 10,
  },
  weekDay: {
    flex: 1,
    textAlign: 'center',
    color: '#8A9098',
    fontSize: 12,
    fontWeight: '700',
  },
  grid: {
    gap: 9,
  },
  gridRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dayCell: {
    width: '13.2%',
    minHeight: 56,
    borderRadius: 12,
    backgroundColor: '#FBFCFE',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.06)',
    paddingVertical: 8,
    shadowColor: '#0A1124',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 1,
  },
  dayCellCompleted: {
    backgroundColor: '#FFF7E2',
    borderColor: 'rgba(201,168,76,0.42)',
  },
  dayCellToday: {
    backgroundColor: '#F2F6FF',
    borderColor: 'rgba(10,17,36,0.3)',
    borderWidth: 1.5,
  },
  dayCellSelected: {
    borderColor: GOLD,
    borderWidth: 2,
    transform: [{ translateY: -1 }],
    shadowColor: GOLD,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.16,
    shadowRadius: 10,
    elevation: 3,
  },
  dayCellEmpty: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    shadowOpacity: 0,
    elevation: 0,
  },
  dayText: {
    color: NAVY,
    fontSize: 15,
    fontWeight: '800',
  },
  dayTextCompleted: {
    color: NAVY,
  },
  dayTextToday: {
    fontWeight: '800',
  },
  dayMetaWrap: {
    minHeight: 12,
    marginTop: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: GOLD,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  editorCard: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 16,
    paddingBottom: 20,
    maxHeight: '86%',
  },
  editorHandle: {
    alignSelf: 'center',
    width: 44,
    height: 5,
    borderRadius: 999,
    backgroundColor: '#D2D8E2',
    marginBottom: 14,
  },
  editorTitle: {
    color: NAVY,
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 4,
  },
  editorSubtitle: {
    color: '#79808A',
    fontSize: 13,
    marginBottom: 8,
  },
  selectedDateText: {
    color: NAVY,
    fontWeight: '700',
    marginBottom: 10,
  },
  fieldTitle: {
    color: NAVY,
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 8,
    marginTop: 8,
  },
  binaryRow: {
    flexDirection: 'row',
    gap: 8,
  },
  binaryBtn: {
    flex: 1,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#CDD7E5',
    backgroundColor: '#F5F8FC',
    paddingVertical: 12,
    alignItems: 'center',
  },
  binaryBtnSelected: {
    backgroundColor: NAVY,
    borderColor: NAVY,
  },
  binaryText: {
    color: NAVY,
    fontSize: 14,
    fontWeight: '700',
  },
  binaryTextSelected: {
    color: '#FFF',
  },
  editorScrollContent: {
    paddingBottom: 8,
  },
  testamentTabs: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
    backgroundColor: '#EFF3F8',
    borderRadius: 18,
    padding: 6,
  },
  testamentTab: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  testamentTabActive: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: 'rgba(10,17,36,0.06)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 1,
  },
  testamentTabIcon: {
    marginBottom: 4,
  },
  testamentTabText: {
    color: '#667085',
    fontSize: 13,
    fontWeight: '700',
  },
  testamentTabTextActive: {
    color: NAVY,
  },
  bookPanel: {
    backgroundColor: '#F8FAFD',
    borderRadius: 18,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E3E8F1',
  },
  bookPanelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  bookPanelTitle: {
    color: NAVY,
    fontSize: 13,
    fontWeight: '800',
  },
  bookPanelCount: {
    color: '#667085',
    fontSize: 12,
    fontWeight: '700',
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  horizontalChipWrap: {
    flexDirection: 'row',
    gap: 8,
    paddingRight: 2,
  },
  bookListScroll: {
    maxHeight: 60,
  },
  bookListContent: {
    flexDirection: 'row',
    gap: 8,
    paddingRight: 2,
  },
  choiceChip: {
    borderWidth: 1,
    borderColor: '#D6DEEA',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: '#FFF',
  },
  bookChoiceChip: {
    minHeight: 44,
    justifyContent: 'center',
    borderRadius: 14,
  },
  bookChoiceChipText: {
    textAlign: 'center',
  },
  choiceChipSelected: {
    borderColor: NAVY,
    backgroundColor: NAVY,
  },
  choiceChipText: {
    color: NAVY,
    fontSize: 13,
    fontWeight: '600',
  },
  choiceChipTextSelected: {
    color: '#FFF',
  },
  modalActionsRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 16,
  },
  closeBtn: {
    flex: 1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: NAVY,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
  },
  closeBtnText: {
    color: NAVY,
    fontSize: 15,
    fontWeight: '700',
  },
  saveBtn: {
    backgroundColor: GOLD,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    flex: 1,
  },
  saveBtnDisabled: {
    opacity: 0.6,
  },
  saveBtnText: {
    color: '#FFF',
    fontSize: 15,
    fontWeight: '800',
  },
});
